### PR TITLE
Remove patching for doc blocks.

### LINKED ISSUE #12696: Adding option to codec to disable patching in Lucene's PFOR encoding
### Description

Background: In https://github.com/Tony-X/search-benchmark-game we were comparing performance of Tantivy and Lucene. "One difference between Lucene and Tantivy is Lucene uses the "patch" FOR, meaning the large values in a block are held out as exceptions so that the remaining values can use a smaller number of bits to encode, a tradeoff of CPU for lower storage space." In https://github.com/Tony-X/search-benchmark-game/issues/46 , I disable the patching in Lucene, to match how Tantivy encodes and run the search-benchmark-game to test the change.

Lucene modifications for testing: I cloned the pforUtil and removed all logic related to patching the exceptions. I modified the Lucene90PostingsReader + Writer to use the util with no patching logic, see sample code https://github.com/slow-J/lucene/commit/83ec5a8b9f7ed39b8aa3ee948ffe5288a9d3fb16
Hardware used: EC2 Graviton2 instance, m6g.4xlarge

Results from the search-benchmark-game: https://github.com/Tony-X/search-benchmark-game/issues/46#issuecomment-1693714327
We saw Lucene's latency improve: -2% in COUNT, -2% in TOP_10_COUNT, -2.07% in TOP_100.

I then ran a Lucene benchmark with [luceneutil](https://github.com/mikemccand/luceneutil) `python3 src/python/localrun.py -source wikimediumall -r`
Hardware used: EC2 instance, m5.12xlarge

Posting results below
```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
            BrowseDateSSDVFacets        0.95      (4.5%)        0.95      (5.9%)   -1.0% ( -10% -    9%) 0.566
               HighTermMonthSort     2558.85      (2.6%)     2539.66      (4.6%)   -0.7% (  -7% -    6%) 0.526
     BrowseRandomLabelSSDVFacets        2.48      (4.3%)        2.47      (1.4%)   -0.7% (  -6% -    5%) 0.486
                         Prefix3      139.77      (1.7%)      139.41      (3.1%)   -0.3% (  -4% -    4%) 0.735
     BrowseRandomLabelTaxoFacets        3.38      (1.5%)        3.37      (1.8%)   -0.2% (  -3% -    3%) 0.689
                          Fuzzy2       50.20      (2.0%)       50.11      (2.1%)   -0.2% (  -4% -    3%) 0.776
                         MedTerm      439.13      (3.9%)      438.94      (4.3%)   -0.0% (  -7% -    8%) 0.974
           BrowseMonthSSDVFacets        3.48      (1.8%)        3.48      (1.5%)    0.0% (  -3% -    3%) 0.949
                         Respell       37.97      (2.9%)       37.99      (2.7%)    0.1% (  -5% -    5%) 0.945
                         LowTerm      323.73      (4.2%)      323.93      (3.9%)    0.1% (  -7% -    8%) 0.960
                          Fuzzy1       45.01      (2.5%)       45.06      (2.6%)    0.1% (  -4% -    5%) 0.896
                        PKLookup      154.24      (2.6%)      154.41      (2.1%)    0.1% (  -4% -    4%) 0.886
                        Wildcard       71.96      (1.4%)       72.04      (1.9%)    0.1% (  -3% -    3%) 0.823
       BrowseDayOfYearSSDVFacets        3.32      (1.8%)        3.33      (1.9%)    0.2% (  -3% -    4%) 0.789
                          IntNRQ       27.77      (8.5%)       27.84      (9.6%)    0.3% ( -16% -   19%) 0.929
                    OrHighNotLow      183.77      (6.9%)      184.66      (5.4%)    0.5% ( -11% -   13%) 0.805
            HighTermTitleBDVSort        4.81      (3.0%)        4.83      (3.0%)    0.5% (  -5% -    6%) 0.566
                        HighTerm      496.37      (5.5%)      499.12      (5.2%)    0.6% (  -9% -   11%) 0.745
                      TermDTSort      109.66      (1.4%)      110.31      (1.3%)    0.6% (  -1% -    3%) 0.155
                HighSloppyPhrase       23.39      (4.2%)       23.56      (3.8%)    0.7% (  -7% -    9%) 0.580
           BrowseMonthTaxoFacets        3.88      (2.5%)        3.91      (1.7%)    0.8% (  -3% -    5%) 0.261
       BrowseDayOfYearTaxoFacets        3.89      (2.5%)        3.92      (0.9%)    0.8% (  -2% -    4%) 0.171
            BrowseDateTaxoFacets        3.88      (2.4%)        3.91      (0.8%)    0.9% (  -2% -    4%) 0.117
                   OrHighNotHigh      270.96      (5.3%)      273.88      (4.2%)    1.1% (  -7% -   11%) 0.474
                    OrHighNotMed      202.84      (6.3%)      205.09      (4.7%)    1.1% (  -9% -   12%) 0.531
            HighIntervalsOrdered        4.36      (4.2%)        4.41      (4.3%)    1.1% (  -7% -   10%) 0.399
               HighTermTitleSort       20.12      (5.5%)       20.35      (5.6%)    1.2% (  -9% -   12%) 0.511
            MedTermDayTaxoFacets        9.42      (3.2%)        9.53      (4.3%)    1.2% (  -6% -    8%) 0.325
                      OrHighHigh       12.07      (4.9%)       12.22      (4.9%)    1.3% (  -8% -   11%) 0.415
                    HighSpanNear        9.92      (3.5%)       10.06      (3.3%)    1.3% (  -5% -    8%) 0.212
                   OrNotHighHigh      356.64      (4.5%)      361.84      (3.3%)    1.5% (  -6% -    9%) 0.242
             MedIntervalsOrdered        3.09      (2.9%)        3.14      (3.0%)    1.5% (  -4% -    7%) 0.119
          OrHighMedDayTaxoFacets        1.54      (4.6%)        1.56      (5.3%)    1.5% (  -8% -   11%) 0.338
                    OrNotHighMed      346.18      (3.3%)      351.65      (3.6%)    1.6% (  -5% -    8%) 0.144
                 LowSloppyPhrase       21.58      (2.6%)       21.94      (2.0%)    1.7% (  -2% -    6%) 0.025
                       OrHighMed       48.51      (3.4%)       49.50      (3.5%)    2.0% (  -4% -    9%) 0.062
                     MedSpanNear       26.76      (1.4%)       27.35      (2.2%)    2.2% (  -1% -    5%) 0.000
           HighTermDayOfYearSort      223.99      (2.7%)      228.97      (2.1%)    2.2% (  -2% -    7%) 0.004
                       OrHighLow      208.96      (3.2%)      213.65      (3.0%)    2.2% (  -3% -    8%) 0.022
                     AndHighHigh       13.93      (3.6%)       14.25      (3.7%)    2.4% (  -4% -   10%) 0.042
                 MedSloppyPhrase       19.45      (2.5%)       19.92      (2.0%)    2.4% (  -1% -    7%) 0.001
        AndHighHighDayTaxoFacets        2.12      (3.9%)        2.17      (5.2%)    2.4% (  -6% -   11%) 0.094
                     LowSpanNear        8.99      (1.6%)        9.24      (1.4%)    2.7% (   0% -    5%) 0.000
             LowIntervalsOrdered        7.46      (2.6%)        7.67      (3.1%)    2.8% (  -2% -    8%) 0.002
                      HighPhrase       12.54      (2.8%)       12.91      (3.3%)    2.9% (  -3% -    9%) 0.003
                       MedPhrase       25.45      (1.8%)       26.22      (2.1%)    3.0% (   0% -    6%) 0.000
         AndHighMedDayTaxoFacets       16.49      (1.7%)       17.08      (2.3%)    3.6% (   0% -    7%) 0.000
                      AndHighMed       91.80      (2.2%)       95.26      (2.3%)    3.8% (   0% -    8%) 0.000
                       LowPhrase      144.04      (1.5%)      150.03      (2.0%)    4.2% (   0% -    7%) 0.000
                    OrNotHighLow      315.83      (1.8%)      330.04      (2.6%)    4.5% (   0% -    9%) 0.000
                      AndHighLow      352.57      (2.7%)      379.44      (3.7%)    7.6% (   1% -   14%) 0.000
```
The tasks at the bottom of the table had the larger QPS improvement.
AndHighLow has a QPS improvement of +7.6%!

Size of test candidate index:   17.626 GiB	total
Size of test baseline index:   18.401 GiB	total

This change would bring a 4.39691% increase in index size.

### Proposal
I propose adding an option to Lucene's codec that allows users to disable patching in the PFOR encoding, providing the option to leverage the performance benefits observed here at a cost of index size.
I would appreciate all feedback and further evaluation of this idea by the Lucene community.

### PR DESCRIPTION
**Pull request by slow-J**
We are still keeping PFOR for positions only.
This is a partial revert of https://github.com/apache/lucene/pull/69 which brings back ForDeltaUtil.

Closes #12696

Starting this as a draft PR since creating the `Lucene99PostingsFormat` brings a lot of change.

Also pending some more benchmarking.

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    final int bitsPerValue = Byte.toUnsignedInt(in.readByte());
+    if (bitsPerValue == 0) {
+      prefixSumOfOnes(longs, base);
+    } else {
+      forUtil.decodeAndPrefixSum(bitsPerValue, in, base, longs);
+    }
+  }
+
+  /** Skip a sequence of 128 longs. */
+  void skip(DataInput in) throws IOException {
```
Comment (jpountz) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java:80]: It looks like we don't need this method as it's only used for tests.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+    }
+  }
+
+  /** Decode deltas, compute the prefix sum and add {@code base} to all decoded longs. */
+  void decodeAndPrefixSum(DataInput in, long base, long[] longs) throws IOException {
+    final int bitsPerValue = Byte.toUnsignedInt(in.readByte());
+    if (bitsPerValue == 0) {
+      prefixSumOfOnes(longs, base);
+    } else {
+      forUtil.decodeAndPrefixSum(bitsPerValue, in, base, longs);
```
Comment (jpountz) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java:75]: Should we inline this other method into this class? It's a bit awkward to have the prefix sum logic in `ForUtil` rather than `ForDeltaUtil`?

Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java:75]: Oh maybe it's for convenience because this other class is generated and not this one?

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/PForUtil.java [hunk 3]
```diff
@@ -0,0 +1,558 @@
...
+      forUtil.decode(bitsPerValue, in, longs);
+    }
+    for (int i = 0; i < numExceptions; ++i) {
+      longs[Byte.toUnsignedInt(in.readByte())] |=
+          Byte.toUnsignedLong(in.readByte()) << bitsPerValue;
+    }
+  }
+
+  /** Decode deltas, compute the prefix sum and add {@code base} to all decoded longs. */
+  void decodeAndPrefixSum(DataInput in, long base, long[] longs) throws IOException {
```
Comment (jpountz) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/PForUtil.java:136]: We could remove this one since we never compute prefix sums on pfor-encoded data anymore.

**Review by jpountz — COMMENTED** [review]
It looks good to me in general. Can you also split `Lucene90PostingsFormat` into a `Lucene90PostingsFormat` that is read-only and a `Lucene90RWPostingsFormat` that is only available for testing?  You can check out `Lucene95RWHnswVectorsFormat` for a recent example of how file formats get split into a read-only implementation and a test-only read-write implementation.

File: lucene/CHANGES.txt [hunk 4]
```diff
@@ -104,6 +104,8 @@ Optimizations
 
 * GITHUB#12552: Make FSTPostingsFormat load FSTs off-heap. (Tony X)
 
+* GITHUB#12696: Change Postings back to using FOR in Lucene99PostingsFormat. (Jakub Slowinski)
```
[the remark this answers is not in the document]
Comment (slow-J) [reply lucene/CHANGES.txt]: Thanks, done in latest commit.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java (hunk 1 above)
Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java]: Thanks, removed in latest commit.

**Comment by slow-J** [comment]
Thanks for the suggestion, I added `Lucene90RWPostingsFormat` in latest commit and made `Lucene90PostingsFormat` read-only.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java (hunk 2 above)
Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene99/ForDeltaUtil.java:75]: I think its the convenience. Otherwise we would have to duplicate about 650 lines of code from `ForUtil`. (all the decode1 -> decode24)

File: lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene90/Lucene90PostingsFormat.java [hunk 5]
```diff
@@ -38,6 +37,8 @@
 /**
  * Lucene 5.0 postings format, which encodes postings in packed integer blocks for fast decode.
```
Comment (gf2121) [inline lucene/backward-codecs/src/java/org/apache/lucene/backward_codecs/lucene90/Lucene90PostingsFormat.java:38]:
```suggestion
 * Lucene 9.0 postings format, which encodes postings in packed integer blocks for fast decode.
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 6]
```diff
@@ -0,0 +1,518 @@
...
+import org.apache.lucene.index.IndexOptions;
+import org.apache.lucene.index.SegmentReadState;
+import org.apache.lucene.index.SegmentWriteState;
+import org.apache.lucene.index.TermState;
+import org.apache.lucene.store.DataOutput;
+import org.apache.lucene.util.IOUtils;
+import org.apache.lucene.util.packed.PackedInts;
+
+/**
+ * Lucene 5.0 postings format, which encodes postings in packed integer blocks for fast decode.
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:39]:
```suggestion
 * Lucene 9.9 postings format, which encodes postings in packed integer blocks for fast decode.
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java [hunk 7]
```diff
@@ -0,0 +1,206 @@
...
+      }
+    } else {
+      posPointer = null;
+    }
+  }
+
+  /**
+   * Trim original docFreq to tell skipReader read proper number of skip points.
+   *
+   * <p>Since our definition in Lucene90Skip* is a little different from MultiLevelSkip* This
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java:93]:
```suggestion
   * <p>Since our definition in Lucene99Skip* is a little different from MultiLevelSkip* This
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java [hunk 8]
```diff
@@ -0,0 +1,206 @@
...
+ * <p>Although this skipper uses MultiLevelSkipListReader as an interface, its definition of skip
+ * position will be a little different.
+ *
+ * <p>For example, when skipInterval = blockSize = 3, df = 2*skipInterval = 6,
+ *
+ * <pre>
+ * 0 1 2 3 4 5
+ * d d d d d d    (posting list)
+ *     ^     ^    (skip point in MultiLeveSkipWriter)
+ *       ^        (skip point in Lucene90SkipWriter)
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java:36]:
```suggestion
 *       ^        (skip point in Lucene99SkipWriter)
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java [hunk 9]
```diff
@@ -0,0 +1,206 @@
...
+ * </pre>
+ *
+ * <p>In this case, MultiLevelSkipListReader will use the last document as a skip point, while
+ * Lucene90SkipReader should assume no skip point will comes.
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java:40]:
```suggestion
 * Lucene99SkipReader should assume no skip point will comes.
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java [hunk 10]
```diff
@@ -0,0 +1,206 @@
...
+ *
+ * <p>If we use the interface directly in Lucene90SkipReader, it may silly try to read another skip
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99SkipReader.java:42]:
```suggestion
 * <p>If we use the interface directly in Lucene99SkipReader, it may silly try to read another skip
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 11]
```diff
@@ -0,0 +1,518 @@
...
+  public static final int BLOCK_SIZE = ForUtil.BLOCK_SIZE;
+
+  /**
+   * Expert: The maximum number of skip levels. Smaller values result in slightly smaller indexes,
+   * but slower skipping in big posting lists.
+   */
+  static final int MAX_SKIP_LEVELS = 10;
+
+  static final String TERMS_CODEC = "Lucene90PostingsWriterTerms";
+  static final String DOC_CODEC = "Lucene90PostingsWriterDoc";
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:368]:
```suggestion
  static final String DOC_CODEC = "Lucene99PostingsWriterDoc";
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 12]
```diff
@@ -0,0 +1,518 @@
...
+  static final String POS_CODEC = "Lucene90PostingsWriterPos";
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:369]:
```suggestion
  static final String POS_CODEC = "Lucene99PostingsWriterPos";
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 13]
```diff
@@ -0,0 +1,518 @@
...
+  static final String PAY_CODEC = "Lucene90PostingsWriterPay";
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:370]:
```suggestion
  static final String PAY_CODEC = "Lucene99PostingsWriterPay";
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 14]
```diff
@@ -0,0 +1,518 @@
...
+ *             frequencies. In particular, PackedDocBlockNum = floor(DocFreq/PackedBlockSize)
+ *         <li>TrimmedDocFreq = DocFreq % PackedBlockSize == 0 ? DocFreq - 1 : DocFreq. We use this
+ *             trick since the definition of skip entry is a little different from base interface.
+ *             In {@link MultiLevelSkipListWriter}, skip data is assumed to be saved for
+ *             skipInterval<sup>th</sup>, 2*skipInterval<sup>th</sup> ... posting in the list.
+ *             However, in Lucene99PostingsFormat, the skip data is saved for
+ *             skipInterval+1<sup>th</sup>, 2*skipInterval+1<sup>th</sup> ... posting
+ *             (skipInterval==PackedBlockSize in this case). When DocFreq is multiple of
+ *             PackedBlockSize, MultiLevelSkipListWriter will expect one more skip data than
+ *             Lucene90SkipWriter.
```
Comment (gf2121) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:222]:
```suggestion
 *             Lucene99SkipWriter.
```

**Review by gf2121 — COMMENTED** [review]
Thanks @slow-J ! I left some minor comments about additional `90` -> `99` refactoring.

**Comment by slow-J** [comment]
> Thanks @slow-J ! I left some minor comments about additional `90` -> `99` refactoring.

Thanks @gf2121 , committed all the suggestions.

**Comment by mikemccand** [comment]
Thanks for tackling this / persisting @slow-J, especially the glorious fun experience of having to "bump" the Codec version ;)  A nice rite-of-passage in this Lucene world!

**Comment by slow-J** [comment]
Thanks @mikemccand and yes, the codec version bump is the majority of this change :D

**Comment by jpountz** [comment]
For reference, I'm interested in taking advantage of the fact we're changing the codec anyway to look into other smaller changes, like switching tail postings from vints to group-varint, or better alignign blocks and skip lists so that `BlockDocsEnum#advance` doesn't need to check whether if `docBufferUpto == BLOCK_SIZE` to decode a new block and could do it directly under the `target > nextSkipDoc` check.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 15]
```diff
@@ -0,0 +1,518 @@
...
+ *         <li>VIntBlock --&gt; &lt;DocDelta[,
+ *             Freq?]&gt;<sup>DocFreq-PackedBlockSize*PackedDocBlockNum</sup>
+ *         <li>SkipData --&gt; &lt;&lt;SkipLevelLength, SkipLevel&gt; <sup>NumSkipLevels-1</sup>,
+ *             SkipLevel&gt;, SkipDatum?
+ *         <li>SkipLevel --&gt; &lt;SkipDatum&gt; <sup>TrimmedDocFreq/(PackedBlockSize^(Level +
+ *             1))</sup>
+ *         <li>SkipDatum --&gt; DocSkip, DocFPSkip, &lt;PosFPSkip, PosBlockOffset, PayLength?,
+ *             PayFPSkip?&gt;?, ImpactLength, &lt;CompetitiveFreqDelta, CompetitiveNormDelta?&gt;
+ *             <sup>ImpactCount</sup>, SkipChildLevelPointer?
+ *         <li>PackedDocDeltaBlock, PackedFreqBlock --&gt; {@link PackedInts PackedInts}
```
Comment (mikemccand) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:177]: Hmm maybe separate out these two to clarify that the `PackedDocDeltaBlock` does not using patching, but the `PackedFreqBlock` does?

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java [hunk 16]
```diff
@@ -0,0 +1,518 @@
...
+ *       randomly. See {@link Lucene90BlockTreeTermsWriter} for more details on the format.
+ * </dl>
+ *
+ * <a id="Frequencies"></a>
+ *
+ * <dl>
+ *   <dd><b>Frequencies and Skip Data</b>
+ *       <p>The .doc file contains the lists of documents which contain each term, along with the
+ *       frequency of the term in that document (except when frequencies are omitted: {@link
+ *       IndexOptions#DOCS}). It also saves skip data to the beginning of each packed or VInt block,
```
Comment (mikemccand) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:161]: Huh, I had thought skip data was saved at the end of each term's postings?  And, the skip data is not stored per block, but rather once for the entire postings list?

(This is a pre-existing issue -- we can fix it separately).

**Review by mikemccand — APPROVED** [review]
Thank you @slow-J -- what a big change this turned out to be.

I left some minor comments that can be resolve later.  I think given how many files this is touching we should merge it sooner rather than later... I'll merge later today if there are no concerns otherwise.

**Comment by mikemccand** [comment]
Thank you @slow-J!

File: lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java (hunk 16 above)
Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99PostingsFormat.java:161]: Opened PR for the 2 javadoc comments: https://github.com/apache/lucene/pull/12776

**Comment by jpountz** [comment]
[Nightly benchmarks](https://home.apache.org/~mikemccand/lucenebench/) just caught up this change, it's no obvious that there is a speedup.

**Comment by gf2121** [comment]
FYI this great [view](https://home.apache.org/~mikemccand/lucenebench/2023.11.09.18.02.58.html) could be easier to see the impact of changes in single day for all tasks. It seems some count tasks get a bit happy with little p-value.

**Comment by slow-J** [comment]
I think that it's a little hard to tell with 1 datapoint due to noise, it seems to be trending upwards in the `BooleanQuery` graphs, but I agree that it's not obvious that there is a noticeable speedup...

**Comment by jpountz** [comment]
Thanks both, I pushed an annotation, it should show up tomorrow. I hah high expectations based on preliminary results from https://github.com/apache/lucene/issues/12696#issue-1950239343 where `AndHighMed` had a reproducible 3-4% speedup, so I was expecting nightlies to show it too. @slow-J I'm curious if you had a chance to run benchmarks on this PR, did it also show a speedup?

**Comment by slow-J** [comment]
I ran a new luceneutil benchmark on Saturday with my commit https://github.com/apache/lucene/commit/8ae598bae593e1faa4ff82a87f4cd45f120f1059 (using Lucene99PostingsFormat) as candidate and the commit's parent as baseline (using Lucene90PostingsFormat).

Other benchmark variables for transparency:
* Java 19
* Ec2 instance: `m5.12xlarge`.
* Disabled JFR

```
                            TaskQPS baseline      StdDevQPS my_modified_version      StdDev                Pct diff p-value
           BrowseMonthTaxoFacets        3.98      (6.7%)        3.92      (2.3%)   -1.7% (  -9% -    7%) 0.286
       BrowseDayOfYearSSDVFacets        3.29      (1.6%)        3.27      (1.1%)   -0.7% (  -3% -    2%) 0.126
            BrowseDateSSDVFacets        1.01      (4.8%)        1.00      (5.6%)   -0.6% ( -10% -   10%) 0.695
                        PKLookup      151.00      (2.5%)      150.26      (2.6%)   -0.5% (  -5% -    4%) 0.543
           BrowseMonthSSDVFacets        3.44      (1.6%)        3.43      (1.5%)   -0.5% (  -3% -    2%) 0.321
                         LowTerm      345.74      (3.0%)      344.39      (3.1%)   -0.4% (  -6% -    5%) 0.689
                        Wildcard      142.48      (1.9%)      142.00      (1.8%)   -0.3% (  -3% -    3%) 0.569
                         Prefix3     1056.96      (4.0%)     1054.07      (3.2%)   -0.3% (  -7% -    7%) 0.812
     BrowseRandomLabelSSDVFacets        2.55      (7.2%)        2.54      (7.2%)   -0.1% ( -13% -   15%) 0.975
       BrowseDayOfYearTaxoFacets        3.96      (0.7%)        3.96      (0.7%)   -0.0% (  -1% -    1%) 0.856
            BrowseDateTaxoFacets        3.94      (0.7%)        3.94      (0.7%)   -0.0% (  -1% -    1%) 0.912
     BrowseRandomLabelTaxoFacets        3.41      (0.8%)        3.41      (0.9%)   -0.0% (  -1% -    1%) 0.977
                          Fuzzy1       69.71      (0.9%)       69.74      (0.8%)    0.0% (  -1% -    1%) 0.902
                   OrHighNotHigh      205.50      (4.6%)      205.67      (5.3%)    0.1% (  -9% -   10%) 0.958
                          Fuzzy2       58.39      (0.8%)       58.44      (0.6%)    0.1% (  -1% -    1%) 0.688
                    OrHighNotLow      265.57      (5.4%)      266.05      (5.9%)    0.2% ( -10% -   12%) 0.921
            HighIntervalsOrdered        5.32      (4.5%)        5.33      (4.1%)    0.2% (  -8% -    9%) 0.879
            HighTermTitleBDVSort        7.81      (3.1%)        7.83      (2.7%)    0.3% (  -5% -    6%) 0.756
                         Respell       34.00      (1.3%)       34.10      (1.1%)    0.3% (  -2% -    2%) 0.451
            MedTermDayTaxoFacets       16.00      (3.8%)       16.04      (3.8%)    0.3% (  -7% -    8%) 0.801
                    OrHighNotMed      255.88      (5.0%)      257.07      (5.2%)    0.5% (  -9% -   11%) 0.774
        AndHighHighDayTaxoFacets        2.83      (3.5%)        2.84      (3.4%)    0.5% (  -6% -    7%) 0.658
                         MedTerm      374.43      (4.9%)      376.51      (5.6%)    0.6% (  -9% -   11%) 0.738
                        HighTerm      472.29      (4.8%)      474.92      (5.7%)    0.6% (  -9% -   11%) 0.738
                     MedSpanNear        5.01      (4.3%)        5.04      (4.6%)    0.6% (  -7% -    9%) 0.690
               HighTermMonthSort     2670.49      (4.1%)     2689.05      (3.1%)    0.7% (  -6% -    8%) 0.549
             LowIntervalsOrdered        6.65      (4.2%)        6.70      (4.3%)    0.7% (  -7% -    9%) 0.584
                      OrHighHigh       22.54      (1.2%)       22.71      (2.4%)    0.7% (  -2% -    4%) 0.204
          OrHighMedDayTaxoFacets        1.58      (4.6%)        1.59      (3.5%)    0.8% (  -6% -    9%) 0.523
                          IntNRQ       27.99      (2.4%)       28.25      (3.9%)    0.9% (  -5% -    7%) 0.371
                   OrNotHighHigh      244.47      (3.7%)      246.97      (4.5%)    1.0% (  -6% -    9%) 0.432
             MedIntervalsOrdered        3.14      (3.7%)        3.18      (3.9%)    1.0% (  -6% -    9%) 0.391
                       OrHighMed       43.19      (1.3%)       43.65      (1.7%)    1.1% (  -1% -    4%) 0.025
                    HighSpanNear        6.73      (2.7%)        6.80      (3.3%)    1.2% (  -4% -    7%) 0.223
                       LowPhrase      255.75      (2.1%)      259.11      (2.0%)    1.3% (  -2% -    5%) 0.043
           HighTermDayOfYearSort      253.38      (4.1%)      257.57      (2.2%)    1.7% (  -4% -    8%) 0.112
                     AndHighHigh       15.70      (1.1%)       15.98      (2.5%)    1.8% (  -1% -    5%) 0.004
                       MedPhrase       14.60      (2.4%)       14.89      (2.2%)    1.9% (  -2% -    6%) 0.009
                       OrHighLow      340.15      (2.3%)      346.84      (2.6%)    2.0% (  -2% -    6%) 0.010
                      HighPhrase      105.17      (2.3%)      107.28      (2.0%)    2.0% (  -2% -    6%) 0.004
                HighSloppyPhrase        1.97      (5.2%)        2.01      (3.6%)    2.0% (  -6% -   11%) 0.152
               HighTermTitleSort      118.65      (5.4%)      121.16      (2.4%)    2.1% (  -5% -   10%) 0.112
                 MedSloppyPhrase        2.73      (5.0%)        2.79      (3.1%)    2.2% (  -5% -   10%) 0.092
                 LowSloppyPhrase        9.48      (3.7%)        9.69      (1.7%)    2.3% (  -3% -    8%) 0.013
                      AndHighMed       47.32      (1.3%)       48.52      (2.8%)    2.5% (  -1% -    6%) 0.000
                     LowSpanNear       17.05      (2.0%)       17.49      (2.1%)    2.6% (  -1% -    6%) 0.000
                    OrNotHighMed      292.37      (3.0%)      300.28      (3.3%)    2.7% (  -3% -    9%) 0.007
         AndHighMedDayTaxoFacets       21.13      (1.8%)       21.74      (1.5%)    2.9% (   0% -    6%) 0.000
                      TermDTSort      124.22      (4.8%)      127.91      (1.3%)    3.0% (  -3% -    9%) 0.008
                      AndHighLow      477.93      (3.1%)      494.29      (2.5%)    3.4% (  -2% -    9%) 0.000
                    OrNotHighLow      424.91      (2.3%)      444.79      (2.8%)    4.7% (   0% -   10%) 0.000
```

and I am still seeing a speed, although the `AndHighMed` gain was 2.5%

**Comment by mikemccand** [comment]
> I ran a new luceneutil benchmark on Saturday with my commit [8ae598b](https://github.com/apache/lucene/commit/8ae598bae593e1faa4ff82a87f4cd45f120f1059) (using Lucene99PostingsFormat) as candidate and the commit's parent as baseline (using Lucene90PostingsFormat).

Is this `wikimediumall` or `wikibigall`?

**Comment by s1monw** [comment]
I wanted to give my $0.02 on this. I am not convinced that a 2% change on a benchmark warrants a 6.2k SLoC addition to such an important codebase. I think the differences in terms of performance between FOR and PFOR vary a lot across benchmarks and are heavily dependent on what your index looks like, how big it is. I would even argue that the space savings PFOR was bringing in (about 5%) might make a bigger difference in terms of performance depending on the size of the index and your hardware. 
I don't wanna go that far and ask for a revert of this change but I think we need to look closer in the future if the rather questionable improvements warrant a change like this or if such a change should rather be  an optional postings format rather than the default.

**Comment by AdityaTeltia** [comment]
Hi @s1monw, 
Hope you are doing well!
I was digging into the reasoning behind Lucene's move from PFOR to FOR in the postings format. From your comment in the discussion, it seems like this change might have introduced a regression rather than an improvement in certain cases.

Was there any consideration given to reverting this change or perhaps adapting `Lucene99PostingsFormat` to use PFOR instead? Or is this behavior more use-case dependent, where FOR performs better under specific conditions?

Would love to understand the trade-offs a bit more, and if there's any ongoing discussion around this.

**Comment by jpountz** [comment]
This change trades higher disk/memory usage in favor of faster queries, it's a trade-off indeed. I don't think there's an ongoing discussion about it anymore, plus we made many efficiency improvements to other areas of query evaluation, so reverting this change would likely result in a noticeable slowdown.

FWIW the higher disk usage will be especially visible on datasets that have dense postings lists (because going from 8 bits per value to 9 is a 12.5% increase while going from 16 to 17 is only a 6.25% increase) and don't have positions (because positions tend dominate disk usage when indexed anyway).

IMO, the current trade-off is quite sensible: FOR for doc IDs, and PFOR for frequency and position blocks.
