### PR TITLE
Only attempt to connect components when entry point is valid

### LINKED ISSUE #13659: TestHnswFloatVectorGraph.testRandomReadWriteAndMerge fails with java.lang.IndexOutOfBoundsException
### Description

```
TestHnswFloatVectorGraph > testRandomReadWriteAndMerge FAILED
    java.lang.IndexOutOfBoundsException: Index 2147483647 out of bounds for length 18
        at __randomizedtesting.SeedInfo.seed([11F871BAF8E02ADC:343906638A98C7FC]:0)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.util.Objects.checkIndex(Objects.java:385)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.apache.lucene.util.hnsw.RandomAccessVectorValues$1.vectorValue(RandomAccessVectorValues.java:135)
        at org.apache.lucene.codecs.hnsw.DefaultFlatVectorScorer$FloatScoringSupplier$1.score(DefaultFlatVectorScorer.java:142)
        at org.apache.lucene.util.hnsw.HnswGraphSearcher.searchLevel(HnswGraphSearcher.java:206)
        at org.apache.lucene.util.hnsw.HnswGraphBuilder.connectComponents(HnswGraphBuilder.java:462)
        at org.apache.lucene.util.hnsw.HnswGraphBuilder.connectComponents(HnswGraphBuilder.java:423)
        at org.apache.lucene.util.hnsw.HnswGraphBuilder.finish(HnswGraphBuilder.java:416)
        at org.apache.lucene.util.hnsw.HnswGraphBuilder.getCompletedGraph(HnswGraphBuilder.java:182)
        at org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsWriter$FieldWriter.getGraph(Lucene99HnswVectorsWriter.java:618)
        at org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsWriter.writeField(Lucene99HnswVectorsWriter.java:187)
        at org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsWriter.flush(Lucene99HnswVectorsWriter.java:149)
        at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.flush(PerFieldKnnVectorsFormat.java:115)
        at org.apache.lucene.index.VectorValuesConsumer.flush(VectorValuesConsumer.java:76)
        at org.apache.lucene.index.IndexingChain.flush(IndexingChain.java:305)
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:456)
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:502)
        at org.apache.lucene.index.DocumentsWriter.maybeFlush(DocumentsWriter.java:456)
        at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:649)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3674)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:4122)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:4084)
        at org.apache.lucene.util.hnsw.HnswGraphTestCase.testRandomReadWriteAndMerge(HnswGraphTestCase.java:189)
        at org.apache.lucene.util.hnsw.TestHnswFloatVectorGraph.testRandomReadWriteAndMerge(TestHnswFloatVectorGraph.java:40)
...
```

### Gradle command to reproduce

./gradlew :lucene:core:test --tests "org.apache.lucene.util.hnsw.TestHnswFloatVectorGraph.testRandomReadWriteAndMerge" -Ptests.jvms=6 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1" -Ptests.seed=11F871BAF8E02ADC -Ptests.locale=hy-AM -Ptests.timezone=America/Vancouver -Ptests.gui=false -Ptests.file.encoding=UTF-8 -Ptests.vectorsize=128 -Ptests.forceintegervectors=true

### PR DESCRIPTION
**Pull request by benwtrent**
We should only connect a component if its entry point is valid.

closes: https://github.com/apache/lucene/issues/13659

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java [hunk 1]
```diff
@@ -456,6 +456,9 @@ private boolean connectComponents(int level) throws IOException {
         if (c != c0) {
           beam.clear();
           eps[0] = c0.start();
+          if (c.start() == NO_MORE_DOCS) {
```
Comment (msokolov) [inline lucene/core/src/java/org/apache/lucene/util/hnsw/HnswGraphBuilder.java:459]: nit: we could move this to the beginning of the loop

**Review by msokolov — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
Belated LGTM.
