### PR TITLE
TestIndexWriterOnVMError.testUnknownError times out (fixes potential IW deadlock on tragic exceptions).

### LINKED ISSUE #12654: TestIndexWriterOnVMError.testUnknownError times out (potential IndexWriter deadlock with tragic exceptions)
### Description

CI indicated the test suite timed out. So, I ran the reproduction line locally and had to kill the test running after 5 minutes.

I seriously doubt this test should take longer than 5 minutes. I ran without the seed and it finished in seconds.

### Gradle command to reproduce

```
./gradlew test --tests TestIndexWriterOnVMError.testUnknownError -Dtests.seed=4A059D04FCC8873 -Dtests.nightly=true -Dtests.locale=rw-RW -Dtests.timezone=Europe/Luxembourg -Dtests.asserts=true -Dtests.file.encoding=UTF-8 -Dtests.multiplier=1
```

### PR DESCRIPTION
**Pull request by dweiss**
Fixes #12654.

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/index/IndexWriter.java [hunk 1]
```diff
@@ -2560,10 +2560,15 @@ private void rollbackInternalNoCommit() throws IOException {
 
           // close all the closeables we can (but important is readerPool and writeLock to prevent
           // leaks)
-          IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
-          writeLock = null;
-          closed = true;
-          closing = false;
+          try {
+            IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
+          } catch (Throwable t) {
```
Comment (s1monw) [inline lucene/core/src/java/org/apache/lucene/index/IndexWriter.java:2565]: I don't think we need that, it will be handled in block below?

File: lucene/core/src/java/org/apache/lucene/index/IndexWriter.java [hunk 2]
```diff
@@ -2560,10 +2560,15 @@ private void rollbackInternalNoCommit() throws IOException {
...
+            throwable.addSuppressed(t);
+          } finally {
+            writeLock = null;
+            closed = true;
+            closing = false;
+          }
 
           // So any "concurrently closing" threads wake up and see that the close has now completed:
           notifyAll();
```
Comment (s1monw) [inline lucene/core/src/java/org/apache/lucene/index/IndexWriter.java:2574]: IMO we should also notify all threads waiting on the monitor in the case of an exception.

**Review by s1monw — CHANGES_REQUESTED** [review]
I left two comments, thanks for opening that

File: lucene/core/src/java/org/apache/lucene/index/IndexWriter.java (hunk 1 above)
Comment (dweiss) [reply lucene/core/src/java/org/apache/lucene/index/IndexWriter.java:2565]: this was deliberate so that notifyAll would still be called, even if something happened. In fact, the finally block is not necessary - it's a drop-through with catch (Throwable), I just wanted to make it explicit that we need to set those fields.

File: lucene/core/src/java/org/apache/lucene/index/IndexWriter.java (hunk 2 above)
Comment (dweiss) [reply lucene/core/src/java/org/apache/lucene/index/IndexWriter.java:2574]: As commented above, it'll be called even if something happens. I didn't want to move that notify out of the synchronized block because this would mean the need to re-acquire the lock?

Comment (s1monw) [reply lucene/core/src/java/org/apache/lucene/index/IndexWriter.java:2574]: not sure we are talking about the same thing. maybe do it like this:

```diff
--- a/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
+++ b/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
@@ -2560,13 +2560,15 @@ public class IndexWriter
 
           // close all the closeables we can (but important is readerPool and writeLock to prevent
           // leaks)
-          IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
-          writeLock = null;
-          closed = true;
-          closing = false;
-
-          // So any "concurrently closing" threads wake up and see that the close has now completed:
-          notifyAll();
+          try {
+            IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
+          } finally {
+            writeLock = null;
+            closed = true;
+            closing = false;
+            // So any "concurrently closing" threads wake up and see that the close has now completed:
+            notifyAll();
+          }
         }
       } catch (Throwable t) {
         throwable.addSuppressed(t);
```

Comment (dweiss) [reply lucene/core/src/java/org/apache/lucene/index/IndexWriter.java:2574]: Ah, I see it now. Sure, I'll move it.  Out of curiosity - what's going to happen if an exception is thrown from here (it's before the synchronization block)?
```
        // Must not hold IW's lock while closing
        // mergeScheduler: this can lead to deadlock,
        // e.g. TestIW.testThreadInterruptDeadlock
        IOUtils.closeWhileHandlingException(mergeScheduler);
```

Comment (s1monw) [reply lucene/core/src/java/org/apache/lucene/index/IndexWriter.java]: yeah you are right, this is also a recipe for deadlocks here... maybe we should do something like this:

```diff
--- a/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
+++ b/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java
@@ -2463,7 +2463,15 @@ public class IndexWriter
     if (infoStream.isEnabled("IW")) {
       infoStream.message("IW", "rollback");
     }
-
+    Closeable cleanupAndNotify =
+        () -> {
+          assert Thread.holdsLock(this);
+          writeLock = null;
+          closed = true;
+          closing = false;
+          // So any "concurrently closing" threads wake up and see that the close has now completed:
+          notifyAll();
+        };
     try {
       synchronized (this) {
         // must be synced otherwise register merge might throw and exception if merges
@@ -2531,43 +2539,35 @@ public class IndexWriter
         // after we leave this sync block and before we enter the sync block in the finally clause
         // below that sets closed:
         closed = true;
-
-        IOUtils.close(writeLock); // release write lock
-        writeLock = null;
-        closed = true;
-        closing = false;
-        // So any "concurrently closing" threads wake up and see that the close has now completed:
-        notifyAll();
+        IOUtils.close(writeLock, cleanupAndNotify); // release write lock
       }
     } catch (Throwable throwable) {
       try {
         // Must not hold IW's lock while closing
         // mergeScheduler: this can lead to deadlock,
         // e.g. TestIW.testThreadInterruptDeadlock
-        IOUtils.closeWhileHandlingException(mergeScheduler);
-        synchronized (this) {
-          // we tried to be nice about it: do the minimum
-          // don't leak a segments_N file if there is a pending commit
-          if (pendingCommit != null) {
-            try {
-              pendingCommit.rollbackCommit(directory);
-              deleter.decRef(pendingCommit);
-            } catch (Throwable t) {
-              throwable.addSuppressed(t);
-            }
-            pendingCommit = null;
-          }
-
-          // close all the closeables we can (but important is readerPool and writeLock to prevent
-          // leaks)
-          IOUtils.closeWhileHandlingException(readerPool, deleter, writeLock);
-          writeLock = null;
-          closed = true;
-          closing = false;
-
-          // So any "concurrently closing" threads wake up and see that the close has now completed:
-          notifyAll();
-        }
+        IOUtils.closeWhileHandlingException(
+            mergeScheduler,
+            () -> {
+              synchronized (this) {
+                // we tried to be nice about it: do the minimum
+                // don't leak a segments_N file if there is a pending commit
+                if (pendingCommit != null) {
+                  try {
+                    pendingCommit.rollbackCommit(directory);
+                    deleter.decRef(pendingCommit);
+                  } catch (Throwable t) {
+                    throwable.addSuppressed(t);
+                  }
+                  pendingCommit = null;
+                }
+                // close all the closeables we can (but important is readerPool and writeLock to
+                // prevent
+                // leaks)
+                IOUtils.closeWhileHandlingException(
+                    readerPool, deleter, writeLock, cleanupAndNotify);
+              }
+            });
       } catch (Throwable t) {
         throwable.addSuppressed(t);
       } finally {
```

Comment (dweiss) [reply lucene/core/src/java/org/apache/lucene/index/IndexWriter.java]: Yep, looks good. I'm sorry for replying late - I was away and couldn't do it properly before. I'll post a patch in a minute.

**Comment by dweiss** [comment]
I pushed the requested changes, @s1monw . No rush, just wanted to let you know.

**Review by s1monw — APPROVED** [review]
LGTM thanks Dawid
