### PR TITLE
Fix jacoco/coverage tasks

### LINKED ISSUE #15677: Code coverage reports failing on main
### Description

https://ci-builds.apache.org/job/Lucene/job/Lucene-Coverage-main/1683/console
```
* Where:
Build file '/home/jenkins/jenkins-agent/workspace/Lucene/Lucene-Coverage-main/build.gradle' line: 20

* What went wrong:
An exception occurred applying plugin request [id: 'lucene.root-project.setup']
> Failed to apply plugin class 'org.apache.lucene.gradle.plugins.java.CodeCoveragePlugin$RootExtPlugin'.
   > Task with name 'jacocoAggregatedReport' not found in root project 'lucene-root'.
```

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

File: build-tools/build-infra/src/main/java/org/apache/lucene/gradle/plugins/java/CodeCoveragePlugin.java [hunk 1]
```diff
@@ -44,10 +46,33 @@ public void apply(Project project) {
...
+                });
+
+        project
+            .getSubprojects()
+            .forEach(
+                p -> {
+                  if (p.file("src/test").exists()) {
+                    project.getDependencies().add("jacocoAggregation", p);
+                  }
+                });
```
Comment (dweiss) [inline build-tools/build-infra/src/main/java/org/apache/lucene/gradle/plugins/java/CodeCoveragePlugin.java:71]: Don't know how to pass an array of lazily computed project refs here (only those that eventually end up being java projects). Provider returning an array/list doesn't work.
