### PR TITLE
Fix termination condition in TestStressNRTReplication.

### LINKED ISSUE #14664: TestStressNRTReplication may never terminate (exceed suite timeout)
### Description

It hangs in the 'restarter' thread on this condition:
```
        while (startupThreads.size() > 0) {
          Thread.sleep(10);
        }
```
the main thread just joins the restarted and never ends. 

The bug is easy to show if you add a sleep before startupThreads.add(t); it is currently invoked after the sub-thread has been started - this means that it is possible the sub-thread removes itself from the startupThreads list before it's added to it, leaving the list in an inconsistent state (and never reach an empty state).

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by dweiss**
Cleans up the code a bit too. Fixes #14664

### CODE REVIEW

File: lucene/replicator/src/test/org/apache/lucene/replicator/nrt/TestStressNRTReplication.java [hunk 1]
```diff
@@ -994,26 +998,26 @@ public void run() {
...
                           startupThreads.remove(Thread.currentThread());
+                          message("N" + idx + ": top: removed thread");
                         }
                       }
                     };
+                startupThreads.add(t);
                 t.setName("start R" + idx);
                 t.start();
-                startupThreads.add(t);
               }
```
Comment (dweiss) [inline lucene/replicator/src/test/org/apache/lucene/replicator/nrt/TestStressNRTReplication.java:1008]: This is the actual fix.

**Review by benwtrent — APPROVED** [review]

**Comment by dweiss** [comment]
Thanks, @benwtrent
