### PR TITLE
Fixes failing test case for TestOrdinalMap.testRamBytesUsed

### LINKED ISSUE #13372: Reproducible failure TestOrdinalMap.testRamBytesUsed
### Description

bisect shows 55ca9f76a06ba025a98cb297db52e21537c55d14 is the first bad commit

```
   >     java.lang.AssertionError: expected:<976> but was:<960>
   >         at __randomizedtesting.SeedInfo.seed([55680AD930225FC5:A7CB1899FA5D4093]:0)
   >         at org.junit.Assert.fail(Assert.java:89)
   >         at org.junit.Assert.failNotEquals(Assert.java:835)
   >         at org.junit.Assert.assertEquals(Assert.java:647)
   >         at org.junit.Assert.assertEquals(Assert.java:633)
   >         at org.apache.lucene.index.TestOrdinalMap.testRamBytesUsed(TestOrdinalMap.java:102)
   >         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

### Gradle command to reproduce

```
./gradlew :lucene:core:test --tests "org.apache.lucene.index.TestOrdinalMap.testRamBytesUsed"  -Ptests.seed=55680AD930225FC5 -Ptests.nightly=true
```

### PR DESCRIPTION
**Pull request by pseudo-nymous**
### Description

closes #13372 

TestOrdinalMap#testRamBytesUsed was failing for the case when there are multiple Default instances for PackedInts.NullReader. Currently, we return 0 when the instance is built with default size i.e. 256. Ref: org.apache.lucene.util.packed.PackedInts.NullReader#ramBytesUsed

But this was not accounted for in the Accumulator being used. Made changes to skip the object if the reader is of default static instance.

Passes failing UT.

`./gradlew :lucene:core:test --tests "org.apache.lucene.index.TestOrdinalMap.testRamBytesUsed" -Ptests.seed=55680AD930225FC5 -Ptests.nightly=true`

### CODE REVIEW

File: lucene/core/src/test/org/apache/lucene/index/TestOrdinalMap.java [hunk 1]
```diff
@@ -52,7 +53,9 @@ public long accumulateObject(
             long shallowSize,
             java.util.Map<Field, Object> fieldValues,
             java.util.Collection<Object> queue) {
-          if (o == LongValues.ZEROES || o == LongValues.IDENTITY) {
+          if (o == LongValues.ZEROES
+              || o == LongValues.IDENTITY
+              || o == PackedInts.NullReader.DEFAULT_PACKED_LONG_VALUES_PAGE_SIZE) {
```
Comment (jpountz) [inline lucene/core/src/test/org/apache/lucene/index/TestOrdinalMap.java:58]: Nit: Can you replace this with `PackedInts.NullReader.forCount(PackedLongValues.DEFAULT_PAGE_SIZE)` and make `DEFAULT_PACKED_LONG_VALUES_PAGE_SIZE` private again?

**Review by jpountz — APPROVED** [review]
The fix looks correct to me, thanks for looking into it!

File: lucene/core/src/test/org/apache/lucene/index/TestOrdinalMap.java (hunk 1 above)
Comment (pseudo-nymous) [reply lucene/core/src/test/org/apache/lucene/index/TestOrdinalMap.java:58]: Sure. Thanks for quick review.

**Review by jpountz — APPROVED** [review]
