### PR TITLE
Fix bug in UnescapedCharSequence and add basic unit tests

### LINKED ISSUE #9049: UnescapedCharSequence Bugs [LUCENE-8001]
There are a couple of issues with UnescapedCharSequence:

1. The [private constructor](https://github.com/apache/lucene-solr/blob/32ed8520c706a865b94e03644ae4e4435e0f7d35/lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java#L52-L63) is not used anywhere (and if it were, it would throw exceptions)
2. The ToEscapedString() overload has an [invalid condition](https://github.com/apache/lucene-solr/blob/32ed8520c706a865b94e03644ae4e4435e0f7d35/lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java#L96) that will only evaluate to true if the string has a length of 0.

There are no tests for UnescapedCharSequence so these issues have gone unnoticed for quite some time.

---
Migrated from [LUCENE-8001](https://issues.apache.org/jira/browse/LUCENE-8001) by Shad Storhaug, updated Oct 21 2017
Linked issues:
 - [LUCENENET-592](https://issues.apache.org/jira/browse/LUCENENET-592)

### PR DESCRIPTION
**Pull request by slow-J**
Fixing a basic bug in UnescapedCharSequence https://github.com/apache/lucene/blob/2bb69f3246218dd8176cf92d8064623688c5272c/lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java#L86
and adding some basic unit tests.
Also removing an unused private constructor.

This is not very urgent since the issue is over 6 years old, but we may as well clean this code up.

Closes #9049.

### CODE REVIEW

File: lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java [hunk 1]
```diff
@@ -101,7 +90,7 @@ public String toStringEscaped() {
    */
   public String toStringEscaped(char[] enabledChars) {
     // TODO: non efficient implementation, refactor this code
```
Comment (slow-J) [inline lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java:92]: In the Lucene codebase this is only ever called with array of length 2, so I didn't refactor......

File: lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java [hunk 2]
```diff
@@ -82,11 +71,11 @@ public String toString() {
...
-      if (this.chars[i] == '\\') {
+    StringBuilder result = new StringBuilder(this.length());
+    for (int i = 0; i < this.length(); i++) {
+      if (this.chars[i] == '\\' || this.wasEscaped[i]) {
         result.append('\\');
-      } else if (this.wasEscaped[i]) result.append('\\');
+      }
 
       result.append(this.chars[i]);
     }
```
Comment (shubhamvishu) [inline lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java:81]: I didn't find any usage of this function as well. Seems its unused too?

**Review by shubhamvishu — APPROVED** [review]
Looks good to me @slow-J

File: lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java (hunk 2 above)
Comment (slow-J) [reply lucene/queryparser/src/java/org/apache/lucene/queryparser/flexible/core/util/UnescapedCharSequence.java:81]: Thanks for the review @shubhamvishu. I only removed the other method because it was `private` and `@SuppressWarnings("unused")`, while this is a potentially useful public method.

File: lucene/CHANGES.txt [hunk 3]
```diff
@@ -138,6 +138,8 @@ Other
 
 * GITHUB#12239: Hunspell: reduced suggestion set dependency on the hash table order (Peter Gromov)
 
+* GITHUB#9049: Removing unused private constructor in UnescapedCharSequence. (Jakub Slowinski)
```
Comment (gsmiller) [inline lucene/CHANGES.txt:141]: Let's have the changes entry highlight the bug fix and not the ctor removal? I don't think we need to mention the removal of an unused, private ctor in CHANGES personally, but users might care about the bug fix :)

Comment (slow-J) [reply lucene/CHANGES.txt]: Good point @gsmiller! Modified the changes.txt to mention the bug fix instead.

**Review by gsmiller — APPROVED** [review]
LGTM! Thanks @slow-J !

**Comment by slow-J** [comment]
Thanks for the review @gsmiller and @shubhamvishu !
