### PR TITLE
Prevent the common zero-width code points and detect invalid UTF-8 encoding in our sources and selected resource files

### LINKED ISSUE #12931: Build should statically detect when an invisible unicode character, such as U+200B (zero width space), sneak into our sources
### Description

Spinoff from #12911 where I hit weird/scary exceptions during `./gradlew regenerate` with certain JDK version(s) and not others due to a lurking zero width space Unicode character.  @uschindler fixed that one case, but perhaps we have others?  And perhaps copy/apply of a patch file is another vector for them to invade us.

Can we statically assert we don't accidentally invite these little buggers in?

### PR DESCRIPTION
**Pull request by uschindler**
This would have prevented the problem with our gradle file. This is just another extension for `validateSourcePatterns` task. We have other bad codepoints already in there, so I'd suggest to add those.

The uFEFF is there two times (first it detects it at begin of file, so we prevent byte order marks, but later it also disallows it; it is duplicate to have different messages).

I also added a strict UTF-8 decoding check when opening the files thanks to @rmuir Code. When a file was accidentally saved in ISO-8859-x or similar bullshit now the source code patterns check reports a violation.

The only violation for zero-width codepoints was a copy-pasted comment in jflex, not relevant to code. There were also 2 CSS files with wrong encoding (changed them to UTF-8).

This fixes #12931

### CODE REVIEW

**Review by dweiss — APPROVED** [review]

**Comment by uschindler** [comment]
Hi, I further improved the source patterns checker and found another violation:

```
Execution failed for task ':lucene:queryparser:validateSourcePatterns'.
> Found 2 source violation(s):
    C:\Users\Uwe Schindler\Projects\lucene\lucene\lucene\queryparser\docs\xml\cctree.js: incorrect UTF-8 encoding [java.nio.charset.MalformedInputException: Input length = 1]
    C:\Users\Uwe Schindler\Projects\lucene\lucene\lucene\queryparser\docs\xml\dtreeStyle.css: incorrect UTF-8 encoding [java.nio.charset.MalformedInputException: Input length = 1]
```

Actually the code now decodes all source files with a REPORTING UTF-8 decoder, so any incorrectly saved ISO-8859-x file will be reported.

This is especially for Robert to be happy (copied his code)!

File: lucene/queryparser/docs/xml/cctree.js [hunk 1]
```diff
@@ -1,16 +1,16 @@
...
-   Copyright (c) 2002-2003 Geir Landr�. Since the original
+   Copyright (c) 2002-2003 Geir Landrö. Since the original
    author didn't clearly forbids copies of this part, we
    assume we're not doing anything wrong in porviding it
    to you, in a modified or non-modified form.
 */
 
 /*   
-   Geir Landr� : Orignal version, for dTree.
+   Geir Landrö : Orignal version, for dTree.
```
Comment (rmuir) [inline lucene/queryparser/docs/xml/cctree.js:13]: what is happening here????

Comment (rmuir) [reply lucene/queryparser/docs/xml/cctree.js:13]: ok, i think this is just an artifact of the github reviewing feature...

**Review by rmuir — APPROVED** [review]

**Comment by uschindler** [comment]
Thanks. I will merge this later to 9.x and main. I'd like to make the reporting a bit better. When a regex matches I'd like to show the fragment around (similar to highlighting).

I think next to the hidden whitespace the best here is that we detect incorrectly encoded UTF-8.

File: lucene/queryparser/docs/xml/cctree.js (hunk 1 above)
Comment (uschindler) [reply lucene/queryparser/docs/xml/cctree.js:13]: Github tries to autodetect the charset and then shows both sides in the detected one. So it looks wrong because on my laptop it detects ISO-8859-1 on the "broken side" and so shows bullshit on the "correct" side.
