### PR TITLE
Fix TestSysoutLimits by making nested test classes not extend LuceneTestCase

### LINKED ISSUE #14307: TestSysoutLimits still occasionally failing
### Description

When run with JDK25.
https://jenkins.thetaphi.de/job/Lucene-10.x-Windows/369/

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by dweiss**
This dodges occasional warnings during randomized setup. Fixes #14307

### CODE REVIEW

File: lucene/test-framework/src/java/org/apache/lucene/tests/util/TestRuleLimitSysouts.java [hunk 1]
```diff
@@ -207,6 +207,7 @@ protected void before() throws Throwable {
       checkCaptureStreams();
     }
     resetCaptureState();
+    var bef = bytesWritten.get();
```
Comment (madrob) [inline lucene/test-framework/src/java/org/apache/lucene/tests/util/TestRuleLimitSysouts.java:210]: did this sneak in?

Comment (dweiss) [reply lucene/test-framework/src/java/org/apache/lucene/tests/util/TestRuleLimitSysouts.java:210]: Ugh. Absolutely - debugging artifact. Thank you!
