### PR TITLE
Fix flaky tests that are caused by small float vectors

### LINKED ISSUE #12940: Test failure in TestKnnGraph.testMultiThreadedSearch
### Description

@msokolov Please take a look when you get a chance!

### Gradle command to reproduce

./gradlew test --tests TestKnnGraph.testMultiThreadedSearch -Dtests.seed=15C41D6B3378DF2B -Dtests.locale=qu-Latn-PE -Dtests.timezone=CST6CDT -Dtests.asserts=true -Dtests.file.encoding=UTF-8

### PR DESCRIPTION
**Pull request by benwtrent**
While quantization generally works well, when the number of dimensions is tiny (just two like in our tests), and we are indexing a circle, and we have random merge policies, we can end up getting unexpected ordering on the resulting vectors.

closes: https://github.com/apache/lucene/issues/12940

### CODE REVIEW

File: lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java [hunk 1]
```diff
@@ -100,22 +100,18 @@ public KnnVectorsFormat getKnnVectorsFormatForField(String field) {
           }
         };
 
-    if (vectorEncoding == VectorEncoding.FLOAT32) {
-      float32Codec = codec;
```
Comment (msokolov) [inline lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java:104]: so this was relying on the default codec being a FLOAT32 codec? TBH I haven't kept up with how we now select whether or not to use quantization. Is it the default? Do we need to override the codec to select it?

Comment (benwtrent) [reply lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java:104]: @msokolov yeah, two tests are really relying on perfect scores & things being float. I mistakenly turned on quantization which adds some error bands to the scores (obviously, because its lossy) and thus its flaky.

Comment (benwtrent) [reply lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java:104]: It could be, I was going to look into that one next.

Comment (msokolov) [reply lucene/core/src/test/org/apache/lucene/index/TestKnnGraph.java:104]: OK that does repro for me, but also on branch_9_8, so I think it must be a different issue - I'll open a new one to track

**Review by msokolov — APPROVED** [review]
