### PR TITLE
Fix race condition on flush for DWPT seqNo generation

### LINKED ISSUE #13127: TestIDVersionPostingsFormat failure
### Description

This failure is not reproducible, which is maybe not too surprising given that the test involves concurrency. A few things are interesting:
 - This is the same failure I had got on https://github.com/apache/lucene/pull/12205 that made me nervous about merging.
 - The seed provided for the recreation configures `checkPendingFlushOnUpdate=false` on the `IndexWriterConfig`, and we recently merged a related optimization: https://github.com/apache/lucene/pull/13115.

This makes me wonder if we have a longstanding problem, which is becoming apparent as we reduce contention on the indexing path.

```
org.apache.lucene.sandbox.codecs.idversion.TestIDVersionPostingsFormat > testGlobalVersions FAILED
    java.lang.AssertionError: maxSeqNo must be greater or equal to 7442 but was 7441
        at __randomizedtesting.SeedInfo.seed([B97A2BDBC7E40BF6:B4D76006D5101E6]:0)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.DocumentsWriterDeleteQueue.close(DocumentsWriterDeleteQueue.java:325)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:659)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:576)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:381)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:355)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:345)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:144)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:52)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
        at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
        at org.apache.lucene.sandbox.codecs.idversion.TestIDVersionPostingsFormat.testGlobalVersions(TestIDVersionPostingsFormat.java:907)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:833)
org.apache.lucene.sandbox.codecs.idversion.TestIDVersionPostingsFormat > test suite's output saved to /opt/buildkite-agent/builds/bk-agent-prod-gcp-1708533031230287464/elastic/apache-lucene-periodic/lucene/sandbox/build/test-results/test/outputs/OUTPUT-org.apache.lucene.sandbox.codecs.idversion.TestIDVersionPostingsFormat.txt, copied below:
   >     java.lang.AssertionError: maxSeqNo must be greater or equal to 7442 but was 7441
   >         at __randomizedtesting.SeedInfo.seed([B97A2BDBC7E40BF6:B4D76006D5101E6]:0)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.DocumentsWriterDeleteQueue.close(DocumentsWriterDeleteQueue.java:325)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:659)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:576)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:381)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:355)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:345)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:144)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:52)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
   >         at org.apache.lucene.core@10.0.0-SNAPSHOT/org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
   >         at org.apache.lucene.sandbox.codecs.idversion.TestIDVersionPostingsFormat.testGlobalVersions(TestIDVersionPostingsFormat.java:907)
   >         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   >         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
   >         at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
   >         at java.base/java.lang.Thread.run(Thread.java:833)
  2> NOTE: reproduce with: gradlew test --tests TestIDVersionPostingsFormat.testGlobalVersions -Dtests.seed=B97A2BDBC7E40BF6 -Dtests.locale=yo-NG -Dtests.timezone=Australia/Broken_Hill -Dtests.asserts=true -Dtests.file.encoding=UTF-8
  2> Feb 21, 2024 4:39:34 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> WARNING: Will linger awaiting termination of 2 leaked thread(s).
  2> NOTE: test params are: codec=CheapBastard, sim=Asserting(RandomSimilarity(queryNorm=false): {id=LM Jelinek-Mercer(0.700000)}), locale=yo-NG, timezone=Australia/Broken_Hill
  2> NOTE: Linux 5.15.0-1051-gcp amd64/Oracle Corporation 17.0.2 (64-bit)/cpus=32,threads=1,free=118531608,total=270532608
  2> NOTE: All tests run in this JVM: [TestIDVersionPostingsFormat]
```

### Gradle command to reproduce

```
gradlew :lucene:sandbox:test --tests "org.apache.lucene.sandbox.codecs.idversion.TestIDVersionPostingsFormat.testGlobalVersions" -Ptests.jvms=12 -Ptests.jvmargs= -Ptests.seed=B97A2BDBC7E40BF6 -Ptests.gui=true -Ptests.file.encoding=US-ASCII -Ptests.vectorsize=128
```

### LINKED ISSUE #13571: DocumentsWriterDeleteQueue.getNextSequenceNumber assertion failure seqNo=9 vs maxSeqNo=8
### Description

I saw the following assertion failure when running TestSnapshotDeletionPolicy#testMultiThreadedSnapshotting

```
Caused by: java.lang.AssertionError: seqNo=9 vs maxSeqNo=8
        at org.apache.lucene.index.DocumentsWriterDeleteQueue.getNextSequenceNumber(DocumentsWriterDeleteQueue.java:567)
        at org.apache.lucene.index.DocumentsWriterDeleteQueue.updateSlice(DocumentsWriterDeleteQueue.java:286)
        at org.apache.lucene.index.DocumentsWriterPerThread.finishDocuments(DocumentsWriterPerThread.java:344)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:284)
        at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:425)
        at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1552)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1837)
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1477)
        at org.apache.lucene.index.TestSnapshotDeletionPolicy$2.run(TestSnapshotDeletionPolicy.java:302)
```

This failure might also be related to #13446 and #13127. Please apply the following patch to reproduce the failure. It takes ~30 seconds to show the error. 

```
diff --git a/lucene/core/src/java/org/apache/lucene/index/ConcurrentApproximatePriorityQueue.java b/lucene/core/src/java/org/apache/lucene/index/ConcurrentApproximatePriorityQueue.java
index 8a8fc72ab4c..12e05293a19 100644
--- a/lucene/core/src/java/org/apache/lucene/index/ConcurrentApproximatePriorityQueue.java
+++ b/lucene/core/src/java/org/apache/lucene/index/ConcurrentApproximatePriorityQueue.java
@@ -38,7 +38,7 @@ final class ConcurrentApproximatePriorityQueue<T> {
     int concurrency = coreCount / 4;
     concurrency = Math.max(MIN_CONCURRENCY, concurrency);
     concurrency = Math.min(MAX_CONCURRENCY, concurrency);
-    return concurrency;
+    return 3;
   }
 
   final int concurrency;
diff --git a/lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java b/lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java
index 7955df5630e..ba3c6f0d3f0 100644
--- a/lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java
+++ b/lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java
@@ -411,8 +411,33 @@ final class DocumentsWriter implements Closeable, Accountable {
       final DocumentsWriterDeleteQueue.Node<?> delNode)
       throws IOException {
     boolean hasEvents = preUpdate();
+    if (Thread.currentThread().getName().contains("t9")) {
+        try {
+            Thread.sleep(100000);
+        } catch (Exception e) {}
+    }
 
+    if (!Thread.currentThread().getName().contains("t0")) {
+      if (Thread.currentThread().getName().contains("t1")) {
+        try {
+          Thread.sleep(5000);
+        } catch (Exception e) {}
+      } else if (Thread.currentThread().getName().contains("t2")) {
+        try {
+          Thread.sleep(5000);
+        } catch (Exception e) {}
+      } else {
+        try {
+          Thread.sleep(1000);
+        } catch (Exception e) {}
+      }
+    }
     final DocumentsWriterPerThread dwpt = flushControl.obtainAndLock();
+    if (!Thread.currentThread().getName().contains("t0") && !Thread.currentThread().getName().contains("t1") && !Thread.currentThread().getName().contains("t2")) {
+      try {
+        Thread.sleep(2000);
+      } catch (Exception e) {}
+    }
     final DocumentsWriterPerThread flushingDWPT;
     long seqNo;
 
@@ -437,6 +462,11 @@ final class DocumentsWriter implements Closeable, Accountable {
       }
       assert dwpt.isHeldByCurrentThread() == false : "we didn't release the dwpt even on abort";
     }
+    if (!Thread.currentThread().getName().contains("t0")) {
+      try {
+        Thread.sleep(50000);
+      } catch (Exception e) {}
+    }
 
     if (postUpdate(flushingDWPT, hasEvents)) {
       seqNo = -seqNo;
@@ -542,6 +572,9 @@ final class DocumentsWriter implements Closeable, Accountable {
 
   synchronized long resetDeleteQueue(int maxNumPendingOps) {
     final DocumentsWriterDeleteQueue newQueue = deleteQueue.advanceQueue(maxNumPendingOps);
+    try {
+      Thread.sleep(5000);
+    } catch (Exception e) {}
     assert deleteQueue.isAdvanced();
     assert newQueue.isAdvanced() == false;
     assert deleteQueue.getLastSequenceNumber() <= newQueue.getLastSequenceNumber();
diff --git a/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java b/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java
index 170966e8ae4..7f04fabb9b2 100644
--- a/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java
+++ b/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterFlushControl.java
@@ -574,6 +574,12 @@ final class DocumentsWriterFlushControl implements Accountable, Closeable {
       } finally {
         perThreadPool.unlockNewWriters();
       }
+      if (Thread.currentThread().getName().contains("t0")) {
+        try {
+          Thread.sleep(5000);
+        } catch (Exception e) {
+        }
+      }
     }
     final List<DocumentsWriterPerThread> fullFlushBuffer = new ArrayList<>();
     for (final DocumentsWriterPerThread next :
diff --git a/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java b/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
index d69a71bfea5..8cc4ce848b7 100644
--- a/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
+++ b/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java
@@ -140,6 +140,11 @@ final class DocumentsWriterPerThreadPool implements Iterable<DocumentsWriterPerT
     final long ramBytesUsed = state.ramBytesUsed();
     assert contains(state)
         : "we tried to add a DWPT back to the pool but the pool doesn't know about this DWPT";
+    if (Thread.currentThread().getName().contains("t0")) {
+      try {
+        Thread.sleep(2000);
+      } catch (Exception e) {}
+    }
     freeList.addAndUnlock(state, ramBytesUsed);
   }

```

Some observations to reproduce the failure:

Basically, one thread tries to close the DocumentsWriterDeleteQueue, but other threads still try to call `getNextSequenceNumber`. Here is the happens-before order:

```
t0: flushControl.obtainAndLock();
t3-t9: flushControl.obtainAndLock();
t0: deleteQueue.advanceQueue(maxNumPendingOps); // maxNumPendingOps = 7
// Here delete queue is updated but not assigned to DocumentWriter.deletetQueue
t3-t9: getNextSequenceNumber()
t1: perThreadPool.getAndLock(); // returns the stale deleteQueue from `freeList`
t1: getNextSequenceNumber()
t2: perThreadPool.getAndLock(); // returns the stale deleteQueue from `freeList`
t2: getNextSequenceNumber()
t0: close // assertion error
```
### Version and environment details

Commit: 33a4c1d8ef999902dacedde9c7f04a3c7e2e78c9
Java version: openjdk 21.0.3 2024-04-16

### PR DESCRIPTION
**Pull request by benwtrent**
There is a tricky race condition with DWPT threads. It is possible that a flush starts by advancing the deleteQueue (in charge of creating seqNo). Thus, the referenced deleteQueue, there should be a cap on the number of actions left. 

However, it is possible after the advance, but before the DWPT are actually marked for flush, the DWPT gets freed and taken again to be used.

To replicate this extreme behavior, see: https://github.com/apache/lucene/compare/main...benwtrent:lucene:test-replicate-and-debug-13127?expand=1

This commit will prevent DWPT from being added back to the free list if their queue has been advanced. This is because the `maxSeqNo` for that queue was created accounting only for the current number of active threads. If the thread gets passed out again and still references the already advanced queue, it is possible that seqNo actually advances past the set `maxSeqNo`. 

closes: https://github.com/apache/lucene/issues/13127
closes: https://github.com/apache/lucene/issues/13571

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java [hunk 1]
```diff
@@ -140,6 +140,11 @@ void marksAsFreeAndUnlock(DocumentsWriterPerThread state) {
     final long ramBytesUsed = state.ramBytesUsed();
     assert contains(state)
         : "we tried to add a DWPT back to the pool but the pool doesn't know about this DWPT";
+    // If we are closed we don't add the DWPT back to the free list. It has to be a "new" DWPT
+    if (state.deleteQueue.isAdvanced()) {
```
[the remark this answers is not in the document]
Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java:144]: Also I wonder if we should rather fix it at the call site in `DocumentsWriter`. It currently looks like this:

```java
      if (dwpt.isFlushPending() || dwpt.isAborted()) {
        dwpt.unlock();
      } else {
        perThreadPool.marksAsFreeAndUnlock(dwpt);
      }
```

Since it already takes care of pending flushes and aborted segments, it would be more consistent to check if the queue is advanced there, e.g. something like this?

```java
      if (dwpt.isFlushPending() || dwpt.isAborted() || dwpt.isQueueAdvanced()) {
        dwpt.unlock();
      } else {
        perThreadPool.marksAsFreeAndUnlock(dwpt);
      }
```

Relatedly, this makes me wonder if there is another way to fix the bug, by somehow marking DWPTs for flush (which prevents them from being reused) before advancing the queue in `DocumentsWriterFlushControl#markForFullFlush`.

**Review by jpountz — COMMENTED** [review]
Woah, so this is the issue that has been haunting us for months. Thank you both for digging!

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (benwtrent) [reply lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java:144]: @jpountz I am adding some asserts to `marksAsFreeAndUnlock` to ensure we aren't calling it if we are pending a flush or aborted or if the queue was advanced. This actually shows another race condition where we call this method sometimes if we are already pending a flush.

I will push up a fix for this as well.

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java [hunk 2]
```diff
@@ -430,10 +430,16 @@ long updateDocuments(
...
     } finally {
-      if (dwpt.isFlushPending() || dwpt.isAborted()) {
-        dwpt.unlock();
-      } else {
-        perThreadPool.marksAsFreeAndUnlock(dwpt);
+      // If a flush is occurring, we don't want to allow this dwpt to be reused
+      // If it is aborted, we shouldn't allow it to be reused
+      // If the deleteQueue is advanced, this means the maximum seqNo has been set and it cannot be
+      // reused
+      synchronized (flushControl) {
```
Comment (benwtrent) [inline lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java:437]: Without this synchronization, I had a test failure where we would trip the new assertions in `marksAsFreeAndUnlock`

This seemed like an obvious race condition to me as we check all these conditions before suggesting the dwpt is available to be used again.

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriterDeleteQueue.java [hunk 3]
```diff
@@ -636,7 +636,7 @@ long getMaxSeqNo() {
   }
 
   /** Returns <code>true</code> if it was advanced. */
-  boolean isAdvanced() {
+  synchronized boolean isAdvanced() {
```
Comment (benwtrent) [inline lucene/core/src/java/org/apache/lucene/index/DocumentsWriterDeleteQueue.java:639]: @jpountz synchronizing per your suggestion. Now isAdvanced and the action that can flip the boolean value are both synchronied.

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java [hunk 4]
```diff
@@ -138,6 +138,15 @@ private synchronized boolean contains(DocumentsWriterPerThread state) {
...
     final long ramBytesUsed = state.ramBytesUsed();
+    assert state.isFlushPending() == false
+            && state.isAborted() == false
+            && state.isQueueAdvanced() == false
+        : "DWPT has pending flush: "
+            + state.isFlushPending()
+            + " aborted="
+            + state.isAborted()
+            + " queueAdvanced="
+            + state.isQueueAdvanced();
```
Comment (benwtrent) [inline lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThreadPool.java:149]: The only place where we call this method is also where we check ALL these conditions. It just seemed prudent to add these assertions as the call flow obviously expects this.

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java (hunk 2 above)
Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java:437]: I played with luceneutil's IndexGeoNames which I've found historically found good at identifying contention at index time. It goes from ~17s (30 threads) to ~20s on my machine, which I suspect is due to this new lock. If it was needed, it would make sense to me (who cares about performance if it's incorrect) but I suspect that it is only needed here to make the assertion in `marksAsFreeAndUnlock` happy?

If I read your previous comments correctly, the point of this assertion is that we cannot write a good test now that the check moved from `DocumentsWriterPerThreadPool` to `DocumentsWriter`. This makes me wonder if we should move all checks (`dwpt.isFlushPending() || dwpt.isAborted() || dwpt.isQueueAdvanced()`) to `DocumentsWriterPerThreadPool` for testability purposes. (Sorry, I realize that this is the opposite from my previous suggestion.)

**Comment by s1monw** [comment]
it might be that my memory is blurry but let me suggest a different way of doing this. When we mark for a full flush in DWPTFlushControl we do lock the DWPTThreadPool for new writers. Once we have done that we can go ahead and set a boolean (let's call it  `stale`) on each of the existing DWPT that it's stale and should be flushed. Then instead of checking `if (perThread.deleteQueue == documentsWriter.deleteQueue) {` in `  DocumentsWriterPerThreadFlushControl obtainAndLock()` we can check for that `stale` and just free that DWPT such that it's not used again. It would then be the same single volatile read? maybe I miss something

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java (hunk 2 above)
Comment (benwtrent) [reply lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java:437]: @jpountz so we are saying it is ok for a DWPT to be marked as free and reusable when `isFlushPending` is true?

Comment (benwtrent) [reply lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java:437]: All this logic is way to opaque and complicated to fully understand all the moving parts for me.

I added my assertions under the assumption that the only method that called this made all those checks previously. 

Without the synchronizing, we will 100% put a DWPT back in for reuse even with `isFlushPending` being true.

**Comment by benwtrent** [comment]
@s1monw I think `deleteQueue.isAdvanced()` is pretty much already this "stale" flag. It indicates that we have solidified how many tasks should be finished and thus we should never reuse it.

**Comment by benwtrent** [comment]
OK, I have confirmed that @s1monw 's proposed fix does work:

```
DocumentsWriterPerThread obtainAndLock() {
     while (closed == false) {
       final DocumentsWriterPerThread perThread = perThreadPool.getAndLock();
-      if (perThread.deleteQueue == documentsWriter.deleteQueue) {
+      if (perThread.deleteQueue.isAdvanced() == false) {
```

And removing the other `isAdvanced()` check in [DocumentsWriter.java](https://github.com/apache/lucene/pull/13627/files#diff-3fa694d9c65c09b06582aa1d76470b931d43f67af81dd7753de7cf15d3d79ed2) still fixes the race condition. 

I can switch to that method if we want. I can also remove the assertions I added @jpountz

File: lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java (hunk 2 above)
Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/index/DocumentsWriter.java:437]: I agree it's too hard to reason about, especially the synchronization logic. Let's make this correct first, we can look into better ways later on.

**Review by jpountz — APPROVED** [review]
