### PR TITLE
Expose the ImpactsEnum impl in Lucene101PostingsFormat.

### LINKED ISSUE #14303: TestScorerUtil.testLikelyImpactsEnum fails
### Description

```
Reproduce with: gradlew :lucene:core:test --tests \
"org.apache.lucene.search.TestScorerUtil.testLikelyImpactsEnum" \
-Ptests.jvms=1 \
-Ptests.jvmargs= \
-Ptests.seed=20E0C716D3EB48E7 \
-Ptests.useSecurityManager=true \
-Ptests.gui=true \
-Ptests.file.encoding=UTF-8 \
-Ptests.vectorsize=512 -Ptests.forceintegervectors=true
```

```
TestScorerUtil > testLikelyImpactsEnum FAILED
    java.lang.AssertionError: expected same:<org.apache.lucene.codecs.lucene101.Lucene101PostingsReader$BlockPostingsEnum@47483778> was not:<org.apache.lucene.search.FilterDocIdSetIterator@3d8bdb0d>
        at __randomizedtesting.SeedInfo.seed([20E0C716D3EB48E7:AC95CC1E9285FC36]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotSame(Assert.java:829)
        at org.junit.Assert.assertSame(Assert.java:772)
        at org.junit.Assert.assertSame(Assert.java:783)
        at org.apache.lucene.search.TestScorerUtil.testLikelyImpactsEnum(TestScorerUtil.java:91)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```

### Gradle command to reproduce

_No response_

### PR DESCRIPTION
**Pull request by jpountz**
This allows access from `ScorerUtil` so that it no longer needs a static block that creates an index to be able to introspect what implementation is used for impacts.

Closes #14303

### CODE REVIEW

**Comment by jpountz** [comment]
I went ahead and merged to step the stream of failures. Happy to revisit the approach in a follow-up if there are concerns.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene101/Lucene101PostingsFormat.java [hunk 1]
```diff
@@ -351,6 +352,14 @@ public final class Lucene101PostingsFormat extends PostingsFormat {
 
   public static final int LEVEL1_MASK = LEVEL1_NUM_DOCS - 1;
 
+  /**
+   * Return the class that implements {@link ImpactsEnum} in this {@link PostingsFormat}. This is
+   * internally used to help the JVM make good inlining decisions.
+   */
+  public static Class<? extends ImpactsEnum> getImpactsEnumImpl() {
```
Comment (uschindler) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene101/Lucene101PostingsFormat.java:359]: maybe add `@lucene.internal` as javadocs tag.

Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene101/Lucene101PostingsFormat.java:359]: Good call, added.
