### PR TITLE
Fix: Lucene90DocValuesProducer.TermsDict.seekCeil doesn't always position bytes correctly (#12167)

### LINKED ISSUE #12167: org.apache.lucene.search.grouping.TestGroupFacetCollector.testRandom fails reproducibly
### Description

Please see https://lists.apache.org/thread/t5hgzv0q177nf8qqyz6h9qhhvwp366gp or https://jenkins.thetaphi.de/job/Lucene-9.x-Linux/8706 for full details.

```
Error Message:
java.lang.IndexOutOfBoundsException: Range [0, 0 + 813) out of bounds for length 80

Stack Trace:
java.lang.IndexOutOfBoundsException: Range [0, 0 + 813) out of bounds for length 80
	at __randomizedtesting.SeedInfo.seed([173F7C2A08C39662:65735925B9A32011]:0)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:180)
	at org.apache.lucene.core@9.6.0-SNAPSHOT/org.apache.lucene.store.ByteBuffersDataInput.readBytes(ByteBuffersDataInput.java:155)
	at org.apache.lucene.core@9.6.0-SNAPSHOT/org.apache.lucene.store.ByteBuffersIndexInput.readBytes(ByteBuffersIndexInput.java:85)
	at org.apache.lucene.test_framework@9.6.0-SNAPSHOT/org.apache.lucene.tests.store.MockIndexInputWrapper.readBytes(MockIndexInputWrapper.java:148)
	at org.apache.lucene.core@9.6.0-SNAPSHOT/org.apache.lucene.codecs.lucene90.Lucene90DocValuesProducer$TermsDict.decompressBlock(Lucene90DocValuesProducer.java:1235)
	at org.apache.lucene.core@9.6.0-SNAPSHOT/org.apache.lucene.codecs.lucene90.Lucene90DocValuesProducer$TermsDict.next(Lucene90DocValuesProducer.java:1093)
	at org.apache.lucene.search.grouping.TermGroupFacetCollector$MV$SegmentResult.nextTerm(TermGroupFacetCollector.java:437)
	at org.apache.lucene.search.grouping.GroupFacetCollector.mergeSegmentResults(GroupFacetCollector.java:97)
	at org.apache.lucene.search.grouping.TestGroupFacetCollector.testRandom(TestGroupFacetCollector.java:429)
...
```

### Gradle command to reproduce

./gradlew test --tests TestGroupFacetCollector.testRandom -Dtests.seed=173F7C2A08C39662 -Dtests.multiplier=3 -Dtests.locale=ru-KZ -Dtests.timezone=America/Mazatlan -Dtests.asserts=true -Dtests.file.encoding=UTF-8

### PR DESCRIPTION
**Pull request by epotyom**
Fix: Lucene90DocValuesProducer.TermsDict.seekCeil doesn't always position bytes correctly (#12167)

TermsDict `ord` and `bytes` can be out of sync after a call to seekCeil. It can lead to a state where `ord` indicates beginning of the next block (`(ord & blockMask) == 0L`), but `bytes` is positioned to read the compressed part of the block.

Test failure in https://github.com/apache/lucene/issues/12167 is triggered when after `seekCeil` we call `next` which needs to `decompressBlock`. We read vInt to `term.length`, where in fact this vInt refers to the compressed block length. This length is greater than max term length of the block, which leads to IndexOutOfBoundsException.
 

TODO: write a test

### CODE REVIEW

**Comment by epotyom** [comment]
Extended existing nightly random tests to catch the issue most of the time. Would that be enough or do we need a test that catches it every single time?

File: lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java [hunk 1]
```diff
@@ -1205,7 +1205,15 @@ public SeekStatus seekCeil(BytesRef text) throws IOException {
           ord = 0;
           return SeekStatus.END;
         } else {
-          seekExact(0L);
+          // seekBlock doesn't update ord and it repositions bytes when calls getFirstTermFromBlock
```
Comment (zhaih) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java:1208]: So, I think the ultimate reason might be previously when we call `seekExact(0)`, this if condition is not true, and thus the `bytes` and `ord` are not reset correctly.
```
      if (ord < this.ord || blockIndex != currentBlockIndex) {
        // The looked up ord is before the current ord or belongs to a different block, seek again
        final long blockAddress = blockAddresses.get(blockIndex);
        bytes.seek(blockAddress);
        this.ord = (blockIndex << TERMS_DICT_BLOCK_LZ4_SHIFT) - 1;
      }
```
So I would prefer we do
```
ord = 1; // Probably need to add some comments on why we do this weird thing
seekExact(0L);
```
Instead of doing it manually here in case we're changing the seek behavior in the future.

**Review by zhaih — COMMENTED** [review]
It would be great if we can have a unit test that can constantly reproduce the previous failure. If my analysis is correct, then probably we just need to reproduce it with
```
te.seekExact(0);
te.seekCeil(new BytesRef());
te.next()
```

**Comment by zhaih** [comment]
Actually I just tried it myself and this will always reproduce the error:
```
        actual.seekExact(0);
        actual.seekCeil(new BytesRef(""));
        for (int i = 0; i < TERMS_DICT_BLOCK_LZ4_SIZE; i++) {
          actual.next();
        }
```
What happened is really tricky:
First, when the bug happens, the `ord` must be 0, otherwise as I previously said everything will be nicely reset by `seekExact(0)`. So only when `ord == 0`, when we call a `seekCeil` with some small value the `ord` and `bytesRef` will be out of sync. 
However at this moment it's totally ok to call `next()` because the next ord is 1 (so we don't need to `decompressBlock`) and we have a `blockInput` that is caching the decompressed bytes when the last time we call `decompressBlock` (remember the `ord` must be 0, so before the `seekCeil`, someone must have already called `decompressBlock` in some way, either `next` or `seekXX`)
The disaster happens when we keep calling `next()` until we have to decompress the next block, as we're previously always using cached `blockInput` so `bytes` kept untouched, and as @epotyom described we read block length and thought it was term length and overfilled the term buffer.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java (hunk 1 above)
Comment (epotyom) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java:1208]: > in case we're changing the seek behavior in the future.

This is the reason why I think we should not rely on seekExact. For example, if we do:

```
ord = 1;
seekExact(0L);
```

and in the future we optimize `seekExact` to not reset `bytes`, this can break again, because seekExact relies on TermDict to be in consistent state. Just to give an example of potential optimization: both ords `0` and `1` are in the same block.  So, when we seek from `1` to `0` we can try using data from the current block without re-reading data from `bytes`?  Even if this particular idea doesn't work, I think that that public methods of this class rely on data to be in a consistent state, so we should probably not rely on them to fix the state?

Comment (zhaih) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java]: That makes sense, can we instead refactor this code with the code below to a method `seekBlock(int)`? Essentially these 4 lines:
```
      final long blockAddress = blockAddresses.get(block);
      this.ord = block << TERMS_DICT_BLOCK_LZ4_SHIFT;
      bytes.seek(blockAddress);
      decompressBlock();
```

File: lucene/core/src/test/org/apache/lucene/codecs/lucene90/TestLucene90DocValuesFormat.java [hunk 2]
```diff
@@ -958,4 +971,61 @@ public void testTermsEnumDictionary() throws IOException {
     reader.close();
     directory.close();
   }
+
+  // Testing termsEnum seekCeil edge case, where inconsistent internal state led to
+  // IndexOutOfBoundsException
+  // see https://github.com/apache/lucene/pull/12555 for details
+  public void testTermsEnumConsistency() throws IOException {
```
Comment (zhaih) [inline lucene/core/src/test/org/apache/lucene/codecs/lucene90/TestLucene90DocValuesFormat.java:978]: Thanks for making the unit test!

**Comment by zhaih** [comment]
Also pls add an entry to CHANGES.txt :)

File: lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java (hunk 1 above)
Comment (epotyom) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducer.java]: Good idea, thanks for the suggestion! We still need to handle `block < 0`, but it looks better now and seekBlock leaves term dict in a consistent state.

**Review by zhaih — APPROVED** [review]
LGTM, thanks!

**Comment by zhaih** [comment]
Merged and backported

**Comment by epotyom** [comment]
@zhaih thank you for reviewing and merging!
