### PR TITLE
Wrap Query rewrite backwards layer with AccessController

### LINKED ISSUE #12304: VirtualMethod does unprivileged reflection access
### Description

In OpenSearch, we've updated to the recent Apache Lucene 9.7 snapshots and got an number of tests failing with `java.security.AccessControlException`. The culprit is `org.apache.lucene.util.VirtualMethod` class that does a number of unprivileged calls to Reflection APIs without using `AccessController.doPrivileged`, a sample stack trace is below:

```
Caused by: java.security.AccessControlException: access denied (\"java.lang.RuntimePermission\" \"accessDeclaredMembers\")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.Class.checkMemberAccess(Class.java:2847)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2471)
	at org.apache.lucene.util.VirtualMethod.reflectImplementationDistance(VirtualMethod.java:139)
	at org.apache.lucene.util.VirtualMethod$1.computeValue(VirtualMethod.java:78)
	at org.apache.lucene.util.VirtualMethod$1.computeValue(VirtualMethod.java:75)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
	at java.base/java.lang.ClassValue.get(ClassValue.java:116)
	at org.apache.lucene.util.VirtualMethod.getImplementationDistance(VirtualMethod.java:111)
	at org.apache.lucene.util.VirtualMethod.compareImplementationDistance(VirtualMethod.java:168)
	at org.apache.lucene.search.Query.<init>(Query.java:54)
	at org.opensearch.join.query.HasChildQueryBuilder$LateParsingQuery.<init>(HasChildQueryBuilder.java:402)
	at org.opensearch.join.query.HasParentQueryBuilder.doToQuery(HasParentQueryBuilder.java:207)
	at org.opensearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:117)
	at org.opensearch.index.query.QueryShardContext.lambda$toQuery$3(QueryShardContext.java:466)
	at org.opensearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:478)
```

I surely know that `SecurityManager` & co are deprecated but Apache Lucene / OpenSearch / Elasticsearch are still relying on it for the time being. 

@uschindler @jpountz the fix is simple (happy to take it and submit a pull request) if there are no objections to make this change in general, cc @nknize 

Sample failing tests:
 - https://build.ci.opensearch.org/job/gradle-check/15584/testReport/junit/org.opensearch.join/ParentChildClientYamlTestSuiteIT/test__yaml__11_parent_child_Parent_child_inner_hits_with_seq_no__3/
 - https://build.ci.opensearch.org/job/gradle-check/15584/testReport/junit/org.opensearch.join/ParentChildClientYamlTestSuiteIT/test__yaml__11_parent_child_Parent_child_inner_hits__2/

### Version and environment details

Latest 9.7.0 snapshots (built of `branch_9x`)

### PR DESCRIPTION
**Pull request by uschindler**
This fixes #12304 for the Query class. The problem was introduced by #12197.

It also adds a note to changes and puts more documentation into `VirtualMethod`. The documentation changes will be forward-ported to main branch.

### CODE REVIEW

**Comment by uschindler** [comment]
Actually to reduce impact of this more we could add an if statement in the Query constructor to not do the override/distance check for Lucene's own classes (as we have all ported to use new API). The problem only affects external classes (and the corresponding Test). We could add a !this.getClass().getName().startsWith("org.apache.lucene.") && AccessController(...) check there.

**Review by benwtrent — APPROVED** [review]
Sorry for missing this 🤦

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Tested locally, the issue is gone, tests pass normally, thanks @uschindler !

File: lucene/core/src/java/org/apache/lucene/search/Query.java [hunk 1]
```diff
@@ -50,8 +52,30 @@ public abstract class Query {
...
   private static final VirtualMethod<Query> newMethod =
       new VirtualMethod<>(Query.class, "rewrite", IndexSearcher.class);
-  private final boolean isDeprecatedRewriteMethodOverridden =
-      VirtualMethod.compareImplementationDistance(this.getClass(), oldMethod, newMethod) > 0;
+  private final boolean isDeprecatedRewriteMethodOverridden;
+
+  /** Constructor for query classes. */
+  public Query() {
+    var clazz = this.getClass();
+    if (clazz.getName().startsWith("org.apache.lucene.")) {
```
Comment (reta) [inline lucene/core/src/java/org/apache/lucene/search/Query.java:60]: Just to note here, both OpenSearch [1] and Elasticsearch [2] host own classes under `org.apache.lucene.` package as well:

[1] https://github.com/opensearch-project/OpenSearch/tree/main/server/src/main/java/org/apache/lucene
[2] https://github.com/elastic/elasticsearch/tree/7.17/server/src/main/java/org/apache/lucene

Comment (uschindler) [reply lucene/core/src/java/org/apache/lucene/search/Query.java:60]: That's an argument to not do this optimization. I also tend to revert my last commit.

I was just thinking about a solution that does not need the extra permission.

**Comment by uschindler** [comment]
Reverted it. I left the fixes of a test calling the deprecated rewrite.

I will merge this tomorrow and forward-port the documentation changes to main.
