### PR TITLE
Fix exponential runtime for Boolean#rewrite

### LINKED ISSUE #12069: Long rewrite times for deeply nested, non-scoring Boolean queries
### Description

When there is deeply nested Boolean clauses, the rewrite time can be exceptionally long in the non-scoring case.

On my machine, this test takes 3+ seconds to run. I suspect its this change: https://github.com/apache/lucene/pull/672

I manually reverted that change, and the rewrite time dropped to 3ms. 

If I changed the top level Boolean clause to `MUST` from `FILTER` (to enable scoring) the rewrite time is ~3ms.

A depth of 20 isn't unheard of, though it is a complicated query. I expect rewrite to take SOME time, but 3+ seconds seems like a bug to me.

Unscientific unit test to confirm performance impact:
```java
public void testDeeplyNestedBooleanRewrite() throws IOException {
    IndexSearcher searcher = newSearcher(new MultiReader());

    Directory dir = newDirectory();
    (new RandomIndexWriter(random(), dir)).close();
    IndexReader r = DirectoryReader.open(dir);
    Supplier<TermQuery> randomTermQuery =
        () ->
            new TermQuery(
                new Term(
                    TestUtil.randomSimpleString(random()), TestUtil.randomSimpleString(random())));
    int depth = 20;
    BooleanQuery deepBuilder = new BooleanQuery.Builder()
            .setMinimumNumberShouldMatch(1)
            .add(randomTermQuery.get(), BooleanClause.Occur.MUST)
            .add(randomTermQuery.get(), BooleanClause.Occur.MUST)
            .build();
    for (int i = 0; i < depth; i++) {
      BooleanQuery.Builder bq = new BooleanQuery.Builder()
              .setMinimumNumberShouldMatch(1)
              .add(randomTermQuery.get(), BooleanClause.Occur.MUST)
              .add(randomTermQuery.get(), BooleanClause.Occur.MUST)
              .add(deepBuilder, BooleanClause.Occur.MUST);
      deepBuilder = bq.build();
    }
    BooleanQuery bq =
        new BooleanQuery.Builder()
            .setMinimumNumberShouldMatch(1)
            .add(deepBuilder, Occur.FILTER)
                .build();
    long start = System.currentTimeMillis();
    searcher.rewrite(bq);
    long finish = System.currentTimeMillis();
    r.close();
    dir.close();
    // Always fail to print
    assertFalse(Long.toString(finish - start), finish > start);
  }
```

### Version and environment details

Lucene version 9.3+

### PR DESCRIPTION
**Pull request by benwtrent**
When https://github.com/apache/lucene/pull/672 was introduced, it added many nice rewrite optimizations. However, in the case when there are many multiple nested `Boolean` queries under a top level `Boolean#filter` clause, its runtime grows exponentially.

The key issue was how the `BooleanQuery#rewriteNoScoring` redirected yet again to the `ConstantScoreQuery#rewrite`. This causes `BooleanQuery#rewrite` to be called again recursively , even though it was previously called in `ConstantScoreQuery#rewrite`, and THEN `BooleanQuery#rewriteNoScoring` is called again, recursively.

This causes exponential growth in rewrite time based on query depth. The change here hopes to short-circuit that and only grow (near) linearly by calling `BooleanQuery#rewriteNoScoring` directly, instead if attempting to redirect through `ConstantScoreQuery#rewrite`.

The absolute worst case I was able to test is many nested `SHOULD` clauses with a depth of 22. This ran for over 7 seconds without my change. With my change it took less than 70ms.

I had to cancel the test (without my change) when the depth was 30. It was simply taking too long. With my change, it was around 100ms.

closes: https://github.com/apache/lucene/issues/12069

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java [hunk 1]
```diff
@@ -203,9 +203,17 @@ BooleanQuery rewriteNoScoring(IndexSearcher indexSearcher) throws IOException {
...
+      // If the clause query is a boolean query, we shouldn't call ConstantScoreQuery#rewrite as
+      // this causes
+      // exponential growth of runtime.
+      if (query instanceof BooleanQuery booleanQuery) {
+        rewritten = booleanQuery.rewriteNoScoring(indexSearcher);
+      } else {
+        rewritten = new ConstantScoreQuery(query).rewrite(indexSearcher);
+        if (rewritten instanceof ConstantScoreQuery constantScoreQuery) {
+          rewritten = constantScoreQuery.getQuery();
+        }
```
Comment (benwtrent) [inline lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java:216]: I have been trying to come up with ideas where calling `new ConstantScoreQuery(query).rewrite(indexSearcher)` when `query instanceof BooleanQuery` is absolutely necessary. But, it seems like it isn't. `ConstantScoreQuery#rewrite` already calls the underlying `query.rewrite` BEFORE attempting the `rewriteNoScoring`.

**Comment by benwtrent** [comment]
@jpountz You probably want to review this one as it relates to your original optimizations.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java [hunk 2]
```diff
@@ -322,6 +323,45 @@ public void testMatchAllMustNot() throws IOException {
...
+    IndexSearcher searcher = newSearcher(new MultiReader());
+
+    Directory dir = newDirectory();
+    (new RandomIndexWriter(random(), dir)).close();
+    IndexReader r = DirectoryReader.open(dir);
+    Function<Integer, TermQuery> termQueryFunction =
+        (i) -> new TermQuery(new Term("layer[" + i + "]", "foo"));
+    int depth = TestUtil.nextInt(random(), 10, 30);
+    TermQuery tq = termQueryFunction.apply(depth);
+    Query expectedQuery = new BooleanQuery.Builder().add(tq, Occur.FILTER).build();
```
Comment (javanna) [inline lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:336]: Would it make sense to write a similar test for boolean queries that do need scoring? I am worried that the wrapping we do in the main rewrite has some impact too but we don't exercise it as much with this test.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java [hunk 3]
```diff
@@ -322,6 +323,45 @@ public void testMatchAllMustNot() throws IOException {
...
+    Query deepBuilder = new BooleanQuery.Builder().add(tq, Occur.MUST).build();
+    for (int i = depth; i > 0; i--) {
+      tq = termQueryFunction.apply(i);
+      // Do this to accurately set setMinimumNumberShouldMatch to the number of should clauses.
+      // This makes setting expectation for rewrite much easier.
+      boolean useShoulds = random().nextBoolean();
```
Comment (javanna) [inline lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:342]: I wonder if we should have a separate test with should clauses, just to simplify the test a bit.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java [hunk 4]
```diff
@@ -322,6 +323,45 @@ public void testMatchAllMustNot() throws IOException {
...
+        expectedBq.add(expectedQuery, Occur.FILTER);
+      }
+      expectedQuery = expectedBq.build();
+    }
+    BooleanQuery bq = new BooleanQuery.Builder().add(deepBuilder, Occur.FILTER).build();
+    expectedQuery = new BoostQuery(new ConstantScoreQuery(expectedQuery), 0.0f);
+    Query rewritten = searcher.rewrite(bq);
+    r.close();
+    dir.close();
+    assertEquals(expectedQuery, rewritten);
```
Comment (javanna) [inline lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:362]: Does this test actually verifies that we are not doing any needless rewriting? I was under the impression that how long the test takes depending on the depth of the boolean query is the only way to catch a regression. Would it be possible to write specific tests that verify the intermediate steps by calling the query rewrite method against some of the intermediate representations of the query and checking what is returned? I have not given this a lot of thought, it may be hard... but I am curious to hear what you think.

**Review by javanna — COMMENTED** [review]
thanks @benwtrent the fix looks good to me, I left a couple of comments.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java (hunk 2 above)
Comment (benwtrent) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:336]: The key issue for the bug was when there was no scoring, and thus fell into the `rewriteNoScoring` case from the CSQ.

All my testing indicates that runtime doesn't exponentially grow when we need scoring as we don't use the CSQ redirect.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java (hunk 4 above)
Comment (benwtrent) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:362]: I wrote this test originally to compare my change with the original implementation. So, I wrote the test to pass the original optimization. Then I verified my change didn't break anything. 

I did use it for checking runtime as well, but that was secondary to making sure I didn't break anything.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java (hunk 2 above)
Comment (benwtrent) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:336]: Also, the wrapping (I think you mean in the CSQ) we do in the main rewrite is ONLY in the non-scoring case, when `BooleanClause.Occur#FILTER` or `BooleanClause.Occur#MUST_NOT`. So, only `BooleanQuery` objects that are under those non-scoring clauses would be wrapped. I am not sure what we would test in this case...

File: lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java (hunk 1 above)
Comment (jpountz) [inline lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java:216]: I'm contemplating replacing your fix with this one which is similar:

```patch
diff --git a/lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java b/lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java
index 0354280eb01..be323bf0e4c 100644
--- a/lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java
+++ b/lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java
@@ -203,7 +203,13 @@ public class BooleanQuery extends Query implements Iterable<BooleanClause> {
 
     for (BooleanClause clause : clauses) {
       Query query = clause.getQuery();
-      Query rewritten = new ConstantScoreQuery(query).rewrite(indexSearcher);
+      // NOTE: rewritingNoScoring() should not call rewrite(), otherwise this
+      // method could run in exponential time with the depth of the query as
+      // every new level would rewrite 2x more than its parent level.
+      Query rewritten = query;
+      if (rewritten instanceof BoostQuery) {
+        rewritten = ((BoostQuery) query).getQuery();
+      }
       if (rewritten instanceof ConstantScoreQuery) {
         rewritten = ((ConstantScoreQuery) rewritten).getQuery();
       }

```

I think it would be a bit more robust, as it would keep working if there are `ConstantScoreQuery` wrappers between the inner levels of `BooleanQuery`s.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java (hunk 4 above)
Comment (jpountz) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:362]: I wonder if we could improve the test by e.g. having a special query implementation that would count the number of times that rewrite() gets called on the innermost query of this tree of queries, and assert that rewrite() has only been called once.

**Review by jpountz — COMMENTED** [review]
Thanks for looking into it! I like that the fix is contained. I left a suggestion for a fix that I think is a bit more robust and for the test.

**Comment by benwtrent** [comment]
@jpountz applied your suggestions

@javanna I added a rewrite count check and split the should & must test.

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java (hunk 4 above)
Comment (benwtrent) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:391]: added verification. It only rewrites once with `MUST`, but `SHOULD` adds some because of how `SHOULD`s change on rewrites.

Comment (javanna) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java:391]: Thanks, this is what I was looking for but I was not sure how to achieve :)

File: lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java [hunk 5]
```diff
@@ -203,9 +203,18 @@ BooleanQuery rewriteNoScoring(IndexSearcher indexSearcher) throws IOException {
...
+      // every new level would rewrite 2x more than its parent level.
+      Query rewritten = query;
+      if (query instanceof BoostQuery) {
+        rewritten = ((BoostQuery) query).getQuery();
+      }
+      if (query instanceof ConstantScoreQuery) {
+        rewritten = ((ConstantScoreQuery) query).getQuery();
+      }
+      if (query instanceof BooleanQuery) {
+        rewritten = ((BooleanQuery) query).rewriteNoScoring(indexSearcher);
```
Comment (javanna) [inline lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java:217]: I believe that we can completely remove the check for boolean query (like Adrien suggested). If we unwrap what's in the boost query the rewriteNoScoring will be taken care of at the next round of rewrite if the inner query is a constant score query. 

That allows us to remove the IndexSearcher argument from this method.

Comment (javanna) [reply lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java:217]: I would make the same change to the main rewrite method. it simplifies things further quite a bit, even if fixing rewriteNoScoring is already fixing the exponential runtime issue.

File: lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java (hunk 1 above)
Comment (javanna) [reply lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java]: It seems like what Adrien is suggested removes the need to artificially wrap which makes me happy :)

File: lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java (hunk 5 above)
Comment (benwtrent) [reply lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java:217]: Without checking for `BooleanQuery`, the number of rewrites on the innermost query are no longer `1` in the `MUST` clause case. 

Removing the recursive `rewriteNoScoring` here, makes the total number of rewrites on the innermost query to equal the depth in the `MUST` clause, and 2*depth in the `SHOULD` clause. 

@jpountz what say you?

File: lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java (hunk 2 above)
Comment (javanna) [reply lucene/core/src/test/org/apache/lucene/search/TestBooleanRewrites.java]: right, I see what you mean. we are good then.

File: lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java (hunk 5 above)
Comment (benwtrent) [reply lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java]: > I would make the same change to the main rewrite method. it simplifies things further quite a bit, even if fixing rewriteNoScoring is already fixing the exponential runtime issue.

I am not sure where you would want to make this change? I suppose I am dense...

I am guessing right here: https://github.com/apache/lucene/blob/7e0b142afeed676c4fc6dc40bbc7fcd277df5c34/lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java#L287

The whole point is to wrap that query as a ConstantScore query. I guess you don't want it wrapped if its boolean and short circuit that to be a rewriteNoScoring. I was trying something along these lines, but then the inner query never got rewritten in the `MUST` case...which was troubling.

But, we can already remove the IndexSearch from the method, which I am doing now in a following commit.

Comment (javanna) [reply lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java]: > I am guessing right here:

yes that is what I had in mind. I was thinking the logic is exactly the same as what we have in rewriteNoScoring and we should be able to align the two. I have observed even less intermediate rewriting in my tests with that additional change. If it complicates things it's not required, I was assuming it does not.

> But, we can already remove the IndexSearch from the method

That's great. It basically enforces that we don't call rewrite (the note you added)  cause we no longer have a searcher to provide to it.

Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/search/BooleanQuery.java]: Sorry for the confusion, my suggestion should have kept the call to rewriteNoScoring on boolean queries, otherwise we're missing simplifications on inner queries.

**Review by jpountz — APPROVED** [review]
This looks great, thank you.

**Review by javanna — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
@benwtrent could you add a changelog entry too?

**Comment by javanna** [comment]
Thanks @benwtrent !
