### PR TITLE
Ensure Nori/Kuromoji shipped binary FST is the latest version

### LINKED ISSUE #12911: Require bundled FSTs to be on the current FST version
### Description

In Lucene 9.9 we bumped the FST version, but we did not re-generate our bundled FSTs such as the ones that are used by our Kuromoji analyzer. IMO we should systematically re-generate such dictionaries when bumping the FST version. Can we fail the build if the version of these dictionaries gets out-of-date?

Note: I don't think it is a bug (at least it should not cause bugs), it's more about making sure our dictionaries get any improvement we make to FSTs immediately.

### PR DESCRIPTION
**Pull request by mikemccand**
Closes #12911

This just adds specific unit tests for the binary FST for Nori's and Kuromoji's `TokenInfoDictionary`.  I had to promote some APIs from private -> package private for test visibility.

I backed out this AM's FST upgrade confirmed the tests fail, with something like this:

```
    java.lang.AssertionError: TokenInfoDictionary's FST is not the latest version: expected 9 but got: 8; run "./gradlew regenerate" to regenerate this FST and all other resources expected:<9> but was:<8>
        at __randomizedtesting.SeedInfo.seed([32EBD74005BEF4E1:C57DC409B3CCC027]:0)
        at junit@4.13.1/org.junit.Assert.fail(Assert.java:89)
        at junit@4.13.1/org.junit.Assert.failNotEquals(Assert.java:835)
        at junit@4.13.1/org.junit.Assert.assertEquals(Assert.java:647)
        at org.apache.lucene.analysis.ja.dict.TestTokenInfoDictionary.testBinaryFSTIsLatestFormat(TestTokenInfoDictionary.java:192)
```

### CODE REVIEW

**Comment by uschindler** [comment]
It would be better to give a more detailed Gradle line like:

```sh
./gradlew :lucene:analysis:nori:regenerate
```

The test is not the nicest looking thing, but I accept it, because it doesn't break classloading of resources. 👍

**Comment by uschindler** [comment]
I never run all regeneration - it doesn't work on Windows and takes very long....

**Review by dungba88 — APPROVED** [review]

**Comment by mikemccand** [comment]
> The test is not the nicest looking thing, but I accept it, because it doesn't break classloading of resources. 👍

Ha!  I take this a strong positive feedback @uschindler ;)

> It would be better to give a more detailed Gradle line like:

OK -- I fixed the exception message to be specific about precisely the regenerate command to run to re-build the one FST (each for Nori and Kuromoji).

I think it's ready -- I'll merge soon and port forward.

File: lucene/core/src/java/org/apache/lucene/util/fst/FST.java [hunk 1]
```diff
@@ -1236,5 +1236,9 @@ public FSTMetadata(
       this.version = version;
       this.numBytes = numBytes;
     }
+
+    public int getVersion() {
```
Comment (uschindler) [inline lucene/core/src/java/org/apache/lucene/util/fst/FST.java:1240]: I think as this is a public class, shouldn't there be javadocs?

**Review by uschindler — APPROVED** [review]
One minor Javadocs related thing, but otherwise it is fine.

**Comment by uschindler** [comment]
> > The test is not the nicest looking thing, but I accept it, because it doesn't break classloading of resources. 👍
> 
> Ha! I take this a strong positive feedback @uschindler ;)

hehe, I was initially thinking about some method in the FST class like `isFSTLatestVersion(InputStream in)`, but I think this is too much abstraction. I was just worried about the code duplication. If we get more Jarred FSTs anywhere else, we can rethink this and move that to LuceneTestCase class.

So all is fine, lets merge this!

File: lucene/core/src/java/org/apache/lucene/util/fst/FST.java (hunk 1 above)
Comment (mikemccand) [reply lucene/core/src/java/org/apache/lucene/util/fst/FST.java:1240]: Ahh good catch -- I'll add.
