### PR TITLE
Fix TestIndexWriterOnError.testIOError failure.

### LINKED ISSUE #13434: TestIndexWriterOnVMError.testUnknownError fails with unclosed file handles
### Description

TestIndexWriterOnVMError.testUnknownError fails reliably with unclosed file handles. It fails in 9x and on main.

On main, the teset name is instead `TestIndexWriterOnError.testUnknownError`

### Gradle command to reproduce

```
./gradlew test --tests TestIndexWriterOnVMError.testUnknownError -Dtests.seed=8701E0F810C16F88 -Dtests.nightly=true -Dtests.locale=fr-GA -Dtests.timezone=America/Tortola -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

### PR DESCRIPTION
**Pull request by jpountz**
Pull request #13406 inadvertly broke Lucene's handling of tragic exceptions by stopping after the first `DocValuesProducer` whose `close()` calls throws an exception, instead of keeping calling `close()` on further producers in the list.

This moves back to the previous behavior.

Closes #13434

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/index/SegmentDocValues.java [hunk 1]
```diff
@@ -76,10 +76,12 @@ synchronized DocValuesProducer getDocValuesProducer(
...
-      assert dvp != null : "gen=" + gen;
-      dvp.decRef();
-    }
+    IOUtils.applyToAll(
+        dvProducersGens.stream().mapToObj(Long::valueOf).toList(),
+        gen -> {
+          RefCount<DocValuesProducer> dvp = genDVProducers.get(gen);
+          assert dvp != null : "gen=" + gen;
+          dvp.decRef();
+        });
```
Comment (benwtrent) [inline lucene/core/src/java/org/apache/lucene/index/SegmentDocValues.java:85]: My only minor concern is that this reverts the minor improvement of using primitive values. But, it fixes a much bigger issue. I am fine with reverting only this part of the optimization that caused the bug.

**Review by benwtrent — APPROVED** [review]

File: lucene/core/src/java/org/apache/lucene/index/SegmentDocValues.java (hunk 1 above)
Comment (bruno-roustant) [reply lucene/core/src/java/org/apache/lucene/index/SegmentDocValues.java:85]: Yes, good catch. This fix is required to continue using IOUtils.
I don't know why I didn't read enough the method javadoc.

**Review by bruno-roustant — APPROVED** [review]
Thank you for the fix
