### PR TITLE
Optimize DocIdSetIteratorAcceptDocs#cost

### LINKED ISSUE #15561: AcceptDocs#cost() fully consumes iterator, invalidating any possible perf gain
### Description

I have been digging into the AcceptDocs API and I noticed the following from the java docs:

```
  /**
   * Return an approximation of the number of accepted documents. This is typically useful to decide
   * whether to consume these accept docs using random access ({@link #bits()}) or sequential access
   * ({@link #iterator()}).
   *
   * <p><b>NOTE</b>: This must not be called after {@link #iterator()}.
   *
   * @return approximate cost
   */
  public abstract int cost() throws IOException;
```

However the implementation for the most common non-cached iterator:

```
    public int cost() throws IOException {
      createBitSetAcceptDocsIfNecessary();
      return acceptBitSet.cardinality();
    }
```

Actually fully consumes the iterator and just calls cardinality (nothing approximate at all...).

Why are we doing that? Why aren't we relying on `DocIdSetIterator#cost` or at least `acceptBitSet.cardinality`?

It seems to me the main idea behind AcceptDocs is the ability to bypass realizing the bitset and to just iterate as normal when the filter is very restrictive...

//cc @shubhamvishu 

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by shubhamvishu**
### Description

We want to avoid realizing the bitset and defer it to `#bits` and rely on approximation to speedup filtered search where filter is very restrictive. See https://github.com/apache/lucene/issues/15561

Closes https://github.com/apache/lucene/issues/15561

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/search/AcceptDocs.java [hunk 1]
```diff
@@ -189,17 +189,23 @@ public Bits bits() throws IOException {
 
     @Override
     public int cost() throws IOException {
-      createBitSetAcceptDocsIfNecessary();
-      return cardinality;
+      if (acceptBitSet != null) {
+        return cardinality;
+      }
+      DocIdSetIterator iterator = iterator();
+      if (liveDocs == null && iterator instanceof BitSetIterator bitSetIterator) {
```
Comment (HUSTERGS) [inline lucene/core/src/java/org/apache/lucene/search/AcceptDocs.java]: Why we need to check whether the iterator is BitSetIterator ? Can we always return the `iterator.cost()`? BitSetIterator#cost() can iternally handle the call?

File: lucene/core/src/java/org/apache/lucene/search/AcceptDocs.java [hunk 2]
```diff
@@ -189,17 +189,23 @@ public Bits bits() throws IOException {
 
     @Override
     public int cost() throws IOException {
-      createBitSetAcceptDocsIfNecessary();
```
Comment (HUSTERGS) [inline lucene/core/src/java/org/apache/lucene/search/AcceptDocs.java:192]: If we remove this line, we should also change the comment above DocIdSetIteratorAcceptDocs ?

File: lucene/core/src/java/org/apache/lucene/search/AcceptDocs.java (hunk 1 above)
Comment (shubhamvishu) [reply lucene/core/src/java/org/apache/lucene/search/AcceptDocs.java]: There were test failures on this codepath(expecting `#getBitset` to be called) but we can change it to instead check `#cost` is called correctly. I like it how it would simplify this given `BitSetIterator` stores the cost at creation time. I'll simplify this.

**Review by benwtrent — APPROVED** [review]
