### PR TITLE
Adjust knn merge stability testing

### LINKED ISSUE #13640: testMergeStability failing for Knn formats
### Description

All KNN formats are periodically failing `testMergeStability`. 

I have verified its due to https://github.com/apache/lucene/pull/13566 

The stability failure is due to a different size in the `vex` (e.g. vector graph connections).

### Gradle command to reproduce

```
./gradlew test --tests TestLucene99HnswScalarQuantizedVectorsFormat.testMergeStability -Dtests.seed=84298DFFA7C134B7 -Dtests.locale=kn -Dtests.timezone=Hongko -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

### PR DESCRIPTION
**Pull request by benwtrent**
With the new connected components work, merging is unstable. It generally seems that between indexing, there might be new connections as `vex` index size increases.

I am not 100% sure the cause here. Opening this PR as one potential solution. Its interesting indeed that it occurs at all.

closes: https://github.com/apache/lucene/issues/13640

### CODE REVIEW

File: lucene/test-framework/src/java/org/apache/lucene/tests/index/RandomCodec.java [hunk 1]
```diff
@@ -191,6 +193,9 @@ public PostingsFormat getPostingsFormatForField(String name) {
       // Safety:
       assert previousMappings.size() < 10000 : "test went insane";
     }
+    if (VERBOSE) {
+      System.out.println("RandomPostingsFormat: " + name + " -> " + codec);
```
Comment (msokolov) [inline lucene/test-framework/src/java/org/apache/lucene/tests/index/RandomCodec.java:197]: Isn't `System.out` forbidden? Or is it OK in tests?

**Review by msokolov — CHANGES_REQUESTED** [review]
seems OK to mark this as unstable, but something is failing in the checks, maybe related to the print statements

File: lucene/test-framework/src/java/org/apache/lucene/tests/index/RandomCodec.java (hunk 1 above)
Comment (benwtrent) [reply lucene/test-framework/src/java/org/apache/lucene/tests/index/RandomCodec.java:197]: Yeah, it's likely forbidden. I found this verbose output helpful in debugging. But I think it can be removed in preference to setting the info stream

I will fix up the PR and merge.
