### PR TITLE
Fix TestShapeDocValues.testLatLonPolygonBBox

### LINKED ISSUE #13531: TestShapeDocValues.testLatLonPolygonBBox
### Description

Saw this fail on some periodic branch tests. 

Reliably repeatable. 

```
  >     java.lang.IllegalArgumentException: at least three non-collinear points required
   >         at __randomizedtesting.SeedInfo.seed([C6E272EBEF02886F:CF2BCB99FBA18A1B]:0)
   >         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:111)
   >         at org.apache.lucene.geo.Tessellator.tessellate(Tessellator.java:89)
   >         at org.apache.lucene.document.LatLonShape.createIndexableFields(LatLonShape.java:102)
   >         at org.apache.lucene.document.LatLonShape.createIndexableFields(LatLonShape.java:86)
   >         at org.apache.lucene.document.TestShapeDocValues.getTessellation(TestShapeDocValues.java:238)
   >         at org.apache.lucene.document.TestShapeDocValues.getTessellation(TestShapeDocValues.java:230)
   >         at org.apache.lucene.document.TestShapeDocValues.computeBoundingBox(TestShapeDocValues.java:140)
   >         at org.apache.lucene.document.TestShapeDocValues.testLatLonPolygonBBox(TestShapeDocValues.java:59)
   >         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
   >         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
   >         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
   >         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
   >         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
   >         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
```

### Gradle command to reproduce

```
./gradlew test --tests TestShapeDocValues.testLatLonPolygonBBox -Dtests.seed=C6E272EBEF02886F -Dtests.locale=mua-Latn-CM -Dtests.timezone=Australia/West -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

### PR DESCRIPTION
**Pull request by shubhamvishu**
### Description

With the culprit seed (`C6E272EBEF02886F`) the generated polygon or triangle have extremely close coordinates(`[(0.0,1.757358717152938E-241), (-4.0378026254892873E-84, 0.0), (-4.0378026254892873E-84, 1.757358717152938E-241)]`) causing the area to overflow the double range (i.e. `4.9E-324` to `1.79E308`).

Closes #13531

### CODE REVIEW

**Comment by msokolov** [comment]
Should we have an epsilon here rather than exact comparison with 0? Usually that's the way of things with floating point checks - we would check |a-b| < epsilon

**Comment by shubhamvishu** [comment]
Yes, usually we do that but in this case there is a catch. This test ONLY fails when the generated points are non collinear(as expected) but the `area == 0` ([checked in this condition](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/geo/Tessellator.java#L1320-L1327)), which makes it throw the error of `at least three non-collinear points required`. If the `area > 0` then this test runs as expected without any issues. So with comparison to 0 we would rightly avoid only those cases where it actually trips but, epsilon might cause it to simply skip more cases where test could have run successfully. Moreover, as the generated coordinates have extremely small absolute values and close distance (eg : SomeNumE-84, SomeNumE-240 etc), its tricky to find some sane epsilon in this case (which would only skip running the test unnecessarily).

File: lucene/core/src/test/org/apache/lucene/document/TestShapeDocValues.java [hunk 1]
```diff
@@ -255,4 +257,9 @@ private List<ShapeField.DecodedTriangle> getTessellation(XYPolygon p) {
     }
     return tess;
   }
+
+  /** Compute signed area of rectangle */
+  private static double area(Polygon p) {
+    return (p.maxLon - p.minLon) * (p.maxLat - p.minLat);
```
Comment (stefanvodita) [inline lucene/core/src/test/org/apache/lucene/document/TestShapeDocValues.java:263]: Isn't it simpler to check the min/max for equality?

Comment (shubhamvishu) [reply lucene/core/src/test/org/apache/lucene/document/TestShapeDocValues.java:263]: Nope, its possible that both the parts of multiplication are `> 0`(non zero) but the result/area is 0 if the result goes beyond the double range(Eg: (`1E-240 * 1E-78` is `0.0`).

**Comment by msokolov** [comment]
>  its tricky to find some sane epsilon in this case (which would only skip running the test unnecessarily)

I agree, and this is fine, but my intuition is there will be some fiddly cases very close to zero that will still fail incorrectly. I guess we'll see?
