### PR TITLE
RegExp: add CASE_INSENSITIVE_RANGE support

### LINKED ISSUE #14378: Case insensitive regex query with character range
### Description

Hi,
I'm implementing regex search in java app with Elasticsearch 8.* and I've noticed unexpected behaviour with `CASE_INSENSITIVE` flag.

It seems that Lucene ignores the flag in case of character ranges and I'm getting the following results when searching fields analyzed by KeywordAnalyzer:

```
"[abc]+" -> "abc", "ABC"
"[ABC]+" ->  "abc", "ABC"
"[a-c]+" -> "abc"
"[A-C]+" -> "ABC"
```

Reproduced in https://github.com/petrsimon/lucene-regex

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by rmuir**
Add optional flag to support case-insensitive ranges. A minimal DFA is always created. This works with Unicode but may have a performance cost.

Each codepoint in the range must be iterated, and any alternatives added to a set. This can be large if the range spans much of Unicode.

CPU and memory costs are contained within a single function enabled by the optional flag. For example when matching a caseless `/[a-z]/`, 54 codepoints will be accumulated into an `int[]`, which is then compressed to 4 ranges before adding to the parse tree.

Closes #14378

Here's what resulting `/[a-z]/` automaton looks like in case you are curious:
```dot
digraph Automaton {
  rankdir = LR
    node [width=0.2, height=0.2, fontsize=8]
    initial [shape=plaintext,label=""]
    initial -> 0
    0 [shape=circle,label="0"]
    0 -> 1 [label="A-Z"]
    0 -> 1 [label="a-z"]
    0 -> 1 [label="ſ"]
    0 -> 1 [label="K"]
    1 [shape=doublecircle,label="1"]
}

```

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java [hunk 1]
```diff
@@ -778,6 +786,53 @@ private int[] toCaseInsensitiveChar(int codepoint) {
...
+          scratch.addTransition(state, state, alt);
+        }
+      } else {
+        int altCase =
+            Character.isLowerCase(i) ? Character.toUpperCase(i) : Character.toLowerCase(i);
+        if (altCase != i) {
+          scratch.addTransition(state, state, altCase);
+        }
+      }
+    }
```
Comment (dweiss) [inline lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:821]: I think this pattern is used in more than one place. Maybe it'd be nicer to make CaseFolding.forAllAlternatives(altCase -> scratch.addTransition(state, state, altCase)) and have all that logic for checking for alternatives embedded in CaseFolding?

**Review by dweiss — APPROVED** [review]
Very nice.

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java (hunk 1 above)
Comment (rmuir) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:821]: good call. this is better than returning mutable arrays that could get messed up by bugs, or creating gazillions of arrays.

Comment (rmuir) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:821]: this one is best as a separate PR. I will work it today.

**Comment by rmuir** [comment]
after fixing the turkish here's the (correct) automaton for `/[a-z]/`: the only special cases are long-s and kelvin sign as you expect:

graphviz (6)

**Comment by rmuir** [comment]
@dweiss thanks for the suggestion there, gazillions of array creations avoided. so now this thing will only spike cpu during parsing at worst. I honestly forget you can pass functions to functions in java now :)
