### PR TITLE
Fix stack overflow in RegExp for long string

### LINKED ISSUE #11537: StackOverflow when RegExp encounters a very large string [LUCENE-10501]
When RegExp encounters a very large string, it hits a Stack Overflow exception when parsing it.

Simple program to repro:
```
$ ls
RegExpTest.java       lucene-core-9.1.0.jar
$ cat RegExpTest.java
class RegExpTest {
    public static void main(String[] args) {
        StringBuilder strBuilder = new StringBuilder();
        for (int i = 0; i < 50000; i++) {
            strBuilder.append("a");
        }
        try {
            new org.apache.lucene.util.automaton.RegExp(strBuilder.toString());
        } catch (StackOverflowError e) {
            System.out.println("Stack overflow");
            System.exit(-1);
        }
        System.out.println("Success");
    }
}
$ javac -cp './lucene-core-9.1.0.jar:.' RegExpTest.java
$ java -cp './lucene-core-9.1.0.jar:.' RegExpTest
Stack overflow
$ java -Xss1G -cp './lucene-core-9.1.0.jar:.' RegExpTest
Success
```
Based on #7218 , this appears to be due to the recursive parsing implementation.

---
Migrated from [LUCENE-10501](https://issues.apache.org/jira/browse/LUCENE-10501) by Kartik Ganesh (@kartg), 1 vote

### PR DESCRIPTION
**Pull request by slow-J**
### Description

Removed recursion from `parseUnionExp`, `parseInterExp` and `parseConcatExp` methods.
This prevents hitting stack overflow errors on long string inputs. Added a unit test to demonstrate.

Closes #11537

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java [hunk 1]
```diff
@@ -30,6 +30,7 @@
 package org.apache.lucene.util.automaton;
 
 import java.io.IOException;
+import java.util.ArrayDeque;
```
Comment (stefanvodita) [inline lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:33]: Are we using `ArrayDeque` because we expect it to be faster than a `Stack`?

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java [hunk 2]
```diff
@@ -1067,22 +1068,44 @@ private boolean check(int flag) {
   }
 
   final RegExp parseUnionExp() throws IllegalArgumentException {
```
Comment (stefanvodita) [inline lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:1070]: These three methods loo similar. Is it worth trying to extract out their bodies to a common method?
This new method would take 3 functions as arguments, one to call in the `do-while` loop, one for the `do-while` condition, and one to call in the `while` loop after.

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java (hunk 1 above)
Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:33]: I am using ArrayDeque because Stack is in forbidden apis, see message:

```
java.util.Stack @ Use more modern java.util.ArrayDeque as it is not 
synchronized
```

Comment (benwtrent) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:33]: `Stack` is old and not preferred. Use `Deque` :)

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java (hunk 2 above)
Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:1070]: Thanks for the suggestion, I will try this and submit a commit with this approach.

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java (hunk 1 above)
Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:33]: Thanks, now using `Deque` type.

**Review by stefanvodita — APPROVED** [review]
Thank you for making the changes!

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java [hunk 3]
```diff
@@ -1067,22 +1071,44 @@ private boolean check(int flag) {
...
+   */
+  @FunctionalInterface
+  private interface MakeRegexGroup {
+    RegExp get(int int1, RegExp exp1, RegExp exp2);
+  }
+
+  final RegExp iterativeParseExp(
+      Supplier<RegExp> gather, BooleanSupplier stop, MakeRegexGroup reduce)
+      throws IllegalArgumentException {
+    Deque<RegExp> regExpStack = new ArrayDeque<>();
```
Comment (zhaih) [inline lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:1101]: Why we need stack/deque even?

If we need to further reduce call stack, then I think we need a **stack that is shared across function calls** and some more rewrite.
But here I don't think we need stack and do any FIFO operations? Should be just:
1. parse all the sub component
2. reduce them

So why not:
```
RegExp res = null;
do {
  RegExp e = gather.get();
  if (res == null) {
    res = e;
  } else {
    res = reduce.get(flags, res, e);
  }
while (stop.getAsBoolean());
```
I think this may alter the result a bit by changing it from `a | (b | (c | d))`  to `((a | b) | c) | d`, but for `union` `intersect` and `concat` the affiliation shouldn't affect the correctness?

**Review by zhaih — CHANGES_REQUESTED** [review]

File: lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java (hunk 3 above)
Comment (stefanvodita) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:1101]: Good point! In these cases, `reduce` is an associative function. If we do this, maybe we can rename it to `associativeReduce` or something similar to make this extra assumption obvious.

Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java:1101]: Thanks for the suggestion Patrick and Stefan.

As long as we do the suggested `reduce.get(flags, res, e)` instead of `reduce.get(flags, e, res)` the result should be correct.

Will rename `reduce` to highlight it's associativeness.

Comment (slow-J) [reply lucene/core/src/java/org/apache/lucene/util/automaton/RegExp.java]: Added a new commit with the changes.

**Review by zhaih — APPROVED** [review]
LGTM

**Review by zhaih — CHANGES_REQUESTED** [review]
@slow-J Please add an entry to CHANGES.txt, I'll merge and backport this one then :)
Thank you!

**Comment by zhaih** [comment]
Merged and backported, thank you @slow-J !
