### PR TITLE
Fix Lucene94HnswVectorsFormat validation on large segments

### LINKED ISSUE #11858: Lucene94HnswVectorsFormat validation fails with large datasets
I ran a test on Lucene 9.4 where I tried to force merge 2 million vectors with
dimension 768. It failed with

```
java.lang.IllegalStateException: Vector data length 3070061568 not matching
size=999369 * dim=768 * byteSize=4 = -1224905728
```

The problem is that we use an integer to represent the size, which is too small
to hold it. The bug snuck in during the work to enable int8 values, which
switched a long to an int: #1054. This error doesn't occur before version 9.4.

### PR DESCRIPTION
**Pull request by jtibshirani**
When reading large segments, the vectors format can fail with a validation
error:

```
java.lang.IllegalStateException: Vector data length 3070061568 not matching
size=999369 * dim=768 * byteSize=4 = -1224905728
```

The problem is that we use an integer to represent the size, which is too small
to hold it. The bug snuck in during the work to enable int8 values, which
switched a long value to an int.

Closes #11858.

### CODE REVIEW

**Comment by iverase** [comment]
I have to change this test  not too long ago to index 4B points instead of 2B to trigger a bug as well. Maybe something like that as a Monster test might work for you? : 
https://github.com/apache/lucene/blob/fe8d11254a8a768608d7bb5e2bf8dcfd2c2c9310/lucene/core/src/test/org/apache/lucene/util/bkd/Test4BBKDPoints.java

**Comment by jtibshirani** [comment]
Thanks @iverase ! Do the monster tests get run regularly (perhaps during nightly builds)?

**Review by msokolov — APPROVED** [review]
LGTM, I am struggling to figure out how to anticipate with better testing. So sorry if this is causing operational woes ... I hope at least that no data was lost? With a new reader can we recover these large indexes?

**Comment by iverase** [comment]
> Do the monster tests get run regularly (perhaps during nightly builds)?

I thought they were running weekly or monthly but checked Apache and Policeman CI and they don't seem to be running.

File: lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java [hunk 1]
```diff
@@ -175,7 +175,7 @@ private void validateFieldEntry(FieldInfo info, FieldEntry fieldEntry) {
           case BYTE -> Byte.BYTES;
           case FLOAT32 -> Float.BYTES;
         };
-    int numBytes = fieldEntry.size * dimension * byteSize;
+    long numBytes = (long) fieldEntry.size * dimension * byteSize;
```
Comment (rmuir) [inline lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java:178]: so we got bit by overflow once here, let's learn from the lesson and use Math.multiplyexact. its just validation code and not performance sensitive.

**Comment by rmuir** [comment]
Without a test, I can't tell that the PR fixes the issue. There might be more problems lurking in other vectors code. We shouldn't play whack-a-mole with releases. I think we should add a Test2BXXX or similar and confirm that "large segments" work correctly.

**Comment by rmuir** [comment]
> I thought they were running weekly or monthly but checked Apache and Policeman CI and they don't seem to be running.

I think they might actually take a week to run :) Nearly all monster tests are this exact same issue but for other formats. For now I think we should just add a vectors version. Initial development of the test and getting it passing may discover more stuff, it means we at least validated for overflow once. And it now becomes possible to run the new monster test on demand (e.g. when voting on 9.4.1 release).

```
$ git grep Monster
lucene/classification/src/test/org/apache/lucene/classification/Test20NewsgroupsClassification.java:@LuceneTestCase.Monster("takes a lot!")
lucene/core/src/test/org/apache/lucene/index/Test2BBinaryDocValues.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BBinaryDocValues.java:@Monster("takes ~ 6 hours if the heap is 5gb")
lucene/core/src/test/org/apache/lucene/index/Test2BDocs.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BDocs.java:@Monster("Takes ~30min")
lucene/core/src/test/org/apache/lucene/index/Test2BNumericDocValues.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BNumericDocValues.java:@Monster("takes ~ 2 hours if the heap is 5gb")
lucene/core/src/test/org/apache/lucene/index/Test2BPoints.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BPoints.java:@Monster("takes at least 4 hours and consumes many GB of temp disk space")
lucene/core/src/test/org/apache/lucene/index/Test2BPositions.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BPositions.java:@Monster("uses lots of space and takes a few minutes")
lucene/core/src/test/org/apache/lucene/index/Test2BPostingsBytes.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BPostingsBytes.java:@Monster("takes ~20GB-30GB of space and 10 minutes")
lucene/core/src/test/org/apache/lucene/index/Test2BSortedDocValuesFixedSorted.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BSortedDocValuesFixedSorted.java:@Monster("Takes ~ 6 hours if the heap is 5gb")
lucene/core/src/test/org/apache/lucene/index/Test2BSortedDocValuesOrds.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BSortedDocValuesOrds.java:@Monster("Takes ~ 6 hours if the heap is 5gb")
lucene/core/src/test/org/apache/lucene/index/Test2BTerms.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test2BTerms.java:@Monster("very slow, use 5g minimum heap")
lucene/core/src/test/org/apache/lucene/index/Test4GBStoredFields.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/index/Test4GBStoredFields.java:@Monster("consumes a lot of disk space")
lucene/core/src/test/org/apache/lucene/index/TestIndexWriterMaxDocs.java:  @Monster("takes over two hours")
lucene/core/src/test/org/apache/lucene/util/Test2BPagedBytes.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/util/Test2BPagedBytes.java:@Monster("You must increase heap to > 2 G to run this")
lucene/core/src/test/org/apache/lucene/util/TestLongBitSet.java:  @Monster("needs hundreds of MB of heap")
lucene/core/src/test/org/apache/lucene/util/bkd/Test4BBKDPoints.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/core/src/test/org/apache/lucene/util/bkd/Test4BBKDPoints.java:@Monster("takes at least 4 hours and consumes many GB of temp disk space")
lucene/facet/src/test/org/apache/lucene/facet/taxonomy/writercache/Test2GBCharBlockArray.java:import org.apache.lucene.tests.util.LuceneTestCase.Monster;
lucene/facet/src/test/org/apache/lucene/facet/taxonomy/writercache/Test2GBCharBlockArray.java:@Monster("uses lots of space and takes a few minutes")
```

File: lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java (hunk 1 above)
Comment (uschindler) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java:178]: Yes please always use Math.multiplyExact(). It is a method call, but it is optimized away as it is an intrinsic.

**Review by uschindler — CHANGES_REQUESTED** [review]

File: lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java (hunk 1 above)
Comment (jtibshirani) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java:178]: 👍

Comment (jtibshirani) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java:178]: I realized I don't totally understand this suggestion. We have three `ints` and we want to compute the product as a `long`. Are you suggesting something like this?

```
long numBytes = Math.multiplyExact(Math.multiplyExact((long) fieldEntry.size, dimension), byteSize);
```

Comment (rmuir) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java:178]: yeah. Maybe on two separate lines so that if it overflows, the stacktrace lets you know exactly which part, for easier debugging?

it may sound like paranoia, but multiplication is rather dangerous with overflow so I think it would be worth it for code like this.

Comment (jtibshirani) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java:178]: Thanks! I'm all about paranoia now after tracking down this issue 😅

Comment (rmuir) [reply lucene/core/src/java/org/apache/lucene/codecs/lucene94/Lucene94HnswVectorsReader.java]: thank you!

**Comment by jtibshirani** [comment]
I'm working on a monster test `TestManyKnnVectors` that indexes a bunch of vectors and force merges. I didn't mention this explicitly, but I also did extensive testing using the Elasticsearch benchmarks that caught the issue, and validated everything works given this fix. Definitely not whacking any moles this release :)

**Comment by rmuir** [comment]
Thank you. There are still many benefits to testing (e.g. -ea flag) vs a benchmark which is generally less picky. Also if there are different supported modes (e.g. 4-byte vs 1-byte) for vectors, in a way that might have different logic/bugs, maybe we can be more exhaustive in the test with it.

**Review by uschindler — APPROVED** [review]
Thanks, change in this issue looks fine. The testing should possibly be a separate issue.

**Comment by jtibshirani** [comment]
Thanks for the reviews! I started to write a monster test, but it will take some time since the iteration cycle is long (each run can take 2+ hours). I'd like to merge this now and get started on a release vote, then follow up with a test. I filed https://github.com/apache/lucene/issues/11863 so we don't drop it. As I mentioned, I did a thorough local test to confirm the fix, and that there aren't other lurking bugs.
