### PR TITLE
Fix duplicate values in org.apache.lucene.analysis.ko.dict.UserDictionary

### LINKED ISSUE #13426: Examine assertion in org.apache.lucene.analysis.ko.dict.UserDictionary
A recent change, #13406 , added an assertion that may be incorrect.

The assertion asserts that the number of entries matches that of the number of inputs processed. This may not be the case then a duplicate entry is passed in. For example,

Add a duplicate entry:
```
$ git diff
diff --git a/lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/userdict.txt b/lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/userdict.txt
index 045b64eaa07..4513885a36b 100644
--- a/lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/userdict.txt
+++ b/lucene/analysis/nori/src/test/org/apache/lucene/analysis/ko/userdict.txt
@@ -5,6 +5,7 @@ C샤프
 세종시 세종 시
 대한민국날씨
 대한민국
+대한민국
 날씨
 21세기대한민국
 세기
\ No newline at end of file
```

```
$ ./gradlew :lucene:analysis:nori:test --tests "org.apache.lucene.analysis.ko.TestKoreanTokenizer"
```

```
reproduce with: gradlew test --tests TestKoreanTokenizer.testPartOfSpeechsWithCompound -Dtests.seed=6445594235429961 -Dtests.locale=bs-BA -Dtests.timezone=Atlantic/Faeroe -Dtests.asserts=true -Dtests.file.encoding=UTF-8
   >     java.lang.AssertionError
   >         at __randomizedtesting.SeedInfo.seed([6445594235429961:9CEA448B4AB5C1F2]:0)
   >         at org.apache.lucene.analysis.ko.dict.UserDictionary.<init>(UserDictionary.java:137)
   >         at org.apache.lucene.analysis.ko.dict.UserDictionary.open(UserDictionary.java:69)
   >         at org.apache.lucene.analysis.ko.TestKoreanTokenizer.readDict(TestKoreanTokenizer.java:51)
   >         at org.apache.lucene.analysis.ko.TestKoreanTokenizer.setUp(TestKoreanTokenizer.java:63)
   >         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
   >         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at junit@4.13.1/org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
   >         at randomizedtesting.runner@2.8.1/com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
   >         at org.apache.lucene.test_framework@10.0.0-SNAPSHOT/org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
...
```

I encountered this assertion firing when testing a snapshot of the Lucene branch with Elasticsearch. The testNoriAnalyzerDuplicateUserDictRuleWithLegacyVersion test fails (hits the assertion), see https://github.com/elastic/elasticsearch/blob/main/plugins/analysis-nori/src/test/java/org/elasticsearch/plugin/analysis/nori/NoriAnalysisTests.java#L132C5-L145C1

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Remove incorrect assertion in org.apache.lucene.analysis.ko.dict.UserDictionary, and replace with array copy if duplicate values are passed.

closes #13426

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
Unless I'm mistaken, this recently added assertion is incorrect, so should simply be removed.

File: lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java [hunk 1]
```diff
@@ -134,7 +134,6 @@ private UserDictionary(List<String> entries) throws IOException {
     this.fst =
         new TokenInfoFST(FST.fromFSTReader(fstCompiler.compile(), fstCompiler.getFSTReader()));
     int[][] segmentations = _segmentations.toArray(new int[_segmentations.size()][]);
-    assert entryIndex == rightIds.length;
```
Comment (bruno-roustant) [inline lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java:137]: The assertion was incorrect, but it detected a problem that needs a code fix.
Can you replace the assertion by
```
if (entryIndex < rightIds.length) {
  rightIds = ArrayUtil.copyOfSubArray(rightIds, 0, entryIndex);
}
```

**Review by bruno-roustant — COMMENTED** [review]
Thanks for starting the fix. The assertion needs to be replaced by some code fix.

File: lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java (hunk 1 above)
Comment (ChrisHegarty) [reply lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java:137]: ha! snap! I just realised same!

**Comment by bruno-roustant** [comment]
The recent code change replaced the previous List<Short> by a primitive structure.
To avoid yet another hppc primitive list in the Lucene fork, this time I replaced by a basic short array. But I missed the duplicate case, and it was not tested.

**Comment by bruno-roustant** [comment]
I'm glad to have added this assertion :) It caught a misunderstanding.

**Review by bruno-roustant — APPROVED** [review]
Thanks for the new test!

**Comment by uschindler** [comment]
Do we have the same issue in kuromoji's UserDictionary? I just want to make sure about this because both nori and kuromoji use similar code.

In @bruno-roustant 's PR where he changed this, he only touched Nor, but just to be sure.

**Comment by ChrisHegarty** [comment]
org.apache.lucene.analysis.ja.dict.UserDictionary looks ok to me - no issue.

**Comment by bruno-roustant** [comment]
The Japanese UserDictionary is quite different, and I didn't touch it. Although I plan later to replace the TreeMap of Integer if possible.

File: lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java [hunk 2]
```diff
@@ -134,7 +135,9 @@ private UserDictionary(List<String> entries) throws IOException {
...
+    if (entryIndex < rightIds.length) {
```
Comment (uschindler) [inline lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java:138]: I would move that up to behind line 103, because that's where rightIds is built and the shorter version should be there.

**Review by uschindler — CHANGES_REQUESTED** [review]

File: lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java (hunk 2 above)
Comment (ChrisHegarty) [reply lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java:135]: I moved it up a couple of lines ( which makes sense ), but it cannot go any further. We only wanna copy once after iterating the values.

Comment (uschindler) [reply lucene/analysis/nori/src/java/org/apache/lucene/analysis/ko/dict/UserDictionary.java:135]: Ah correct. I thought the loop ended after 103.

The original code looked like this.

**Review by uschindler — APPROVED** [review]
