### PR TITLE
[Tessellator] Improve the checks that validate the diagonal between two polygon nodes

### LINKED ISSUE #12352: Polygons failing to tessellate
relates to https://github.com/apache/lucene/issues/11986

More polygons reported to be failing to tessellate. The polygon data can be found here: Sharing the sample polygon data.
[https://raw.githubusercontent.com/amalantonygit/polygon-data/main/polygon.geojson](https://raw.githubusercontent.com/amalantonygit/polygon-data/main/polygon.geojson)

image

From a first look, the error seems related to the way we validate the diagonal chosen to split polygons here: https://github.com/apache/lucene/blob/0c293909c050e2f24ef5a6062d8da31e6595e8cd/lucene/core/src/java/org/apache/lucene/geo/Tessellator.java#L1093

### PR DESCRIPTION
**Pull request by iverase**
The new checks make sure we always generate two valid CW polygons. 
I tried this change with my own dataset of 400 million polygons and everything passes.

fixes https://github.com/apache/lucene/issues/12352

@craigtaverner would you mind having a look?

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/geo/Tessellator.java [hunk 1]
```diff
@@ -1090,17 +1090,22 @@ private static final Node splitPolygon(final Node a, final Node b, boolean edgeF
    * Determines whether a diagonal between two polygon nodes lies within a polygon interior. (This
    * determines the validity of the ray.) *
    */
-  private static final boolean isValidDiagonal(final Node a, final Node b) {
+  private static boolean isValidDiagonal(final Node a, final Node b) {
+    if (a.next.idx == b.idx
+        || a.previous.idx == b.idx
+        // check next edges are locally visible
+        || isLocallyInside(a.previous, b) == false
```
Comment (craigtaverner) [inline lucene/core/src/java/org/apache/lucene/geo/Tessellator.java:1097]: I thought the `== false` pattern was an elasticsearch pattern, not a lucene pattern?

**Review by craigtaverner — APPROVED** [review]
LGTM
