### PR TITLE
Remove broken .toArray from IntObjectHashMap entirely

### LINKED ISSUE #13761: IntObjectHashMap.values().toArray() method throws ClassCastException
### Description

The ClassCastEx is thrown when the `IntObjectHashMap.values().toArray()` method is called with a type other than `Object`, and of course the same exception occurs with `CharObjectHashMap` and `LongObjectHashMap`. The issue can be reproduced with the following test.
```
@Test
  public void testStringMapValues() {
    IntObjectHashMap<String> map = new IntObjectHashMap<>();
    map.put(1, "a");
    map.put(2, "b");
    map.put(3, "c");
    String[] values = map.values().toArray();
  }
```

There are several options to fix the issue.
1. change the return value to `Object[]`;
2. mimic the `ArrayList.toArray(T[])` method to pass a `T[]` parameter;
3. replace the `toArray` method with a `asList` method, and return a `List<T>`.

IMO, either option 2 or 3 would be acceptable. Any thought?

### Version and environment details

_No response_

### PR DESCRIPTION
**Pull request by dweiss**
This method is only used in tests. I moved the toList collection utility to the test class to minimize surface API. 
Fixes #13761

### CODE REVIEW

File: lucene/core/src/test/org/apache/lucene/internal/hppc/TestIntObjectHashMap.java [hunk 1]
```diff
@@ -66,10 +69,8 @@ private static void assertSortedListEquals(int[] array, int... elements) {
   }
 
   /** Check if the array's content is identical to a given sequence of elements. */
-  private static void assertSortedListEquals(Object[] array, Object... elements) {
-    assertEquals(elements.length, array.length);
-    Arrays.sort(array);
-    assertArrayEquals(elements, array);
+  private static void assertSortedListEquals(List<Object> array, Object... elements) {
+    Assert.assertEquals(array.stream().sorted().toList(), Arrays.asList(elements));
```
Comment (bruno-roustant) [inline lucene/core/src/test/org/apache/lucene/internal/hppc/TestIntObjectHashMap.java:73]: Should the params order be swapped to have the expected first?

**Review by bruno-roustant — APPROVED** [review]

File: lucene/core/src/test/org/apache/lucene/internal/hppc/TestIntObjectHashMap.java (hunk 1 above)
Comment (dweiss) [reply lucene/core/src/test/org/apache/lucene/internal/hppc/TestIntObjectHashMap.java:73]: Absolutely - thank you for spotting this.
