### PR TITLE
fix overflows in compound assignments

### LINKED ISSUE #11932: one-time pass thru error-prone NarrowingCompoundAssignment check
### Description

A great overflow issue: https://errorprone.info/bugpattern/NarrowingCompoundAssignment

javac is getting its own checker for this in version 20 so eventually we can switch to that one. But for now, i'd like to try to enable the error-prone version.

in a nutshell, compound assignment operators are totally lenient:
```
jshell> byte x = 0;
x ==> 0

jshell> x = x + Long.MAX_VALUE;
|  Error:
|  incompatible types: possible lossy conversion from long to byte
|  x = x + Long.MAX_VALUE;
|      ^----------------^

jshell> x += Long.MAX_VALUE;
$2 ==> -1
```

### PR DESCRIPTION
**Pull request by rmuir**
Fixes found from #11932 review of narrowing-compound-assignments

The checker is noisy, so it isn't being enabled here. Just fixing the rare gems that look reasonable.

Feel free to push commits here if you find stuff in that log file.

Closes #11932

### CODE REVIEW

File: lucene/core/src/java/org/apache/lucene/codecs/KnnVectorsWriter.java [hunk 1]
```diff
@@ -108,7 +108,7 @@ public int nextDoc() throws IOException {
   protected static class MergedVectorValues extends VectorValues {
     private final List<VectorValuesSub> subs;
     private final DocIDMerger<VectorValuesSub> docIdMerger;
-    private final int cost;
+    private final long cost;
```
Comment (jpountz) [inline lucene/core/src/java/org/apache/lucene/codecs/KnnVectorsWriter.java:111]: Maybe we should remove `cost` altogether here. It's redundant with `size` on vectors?

Comment (jpountz) [reply lucene/core/src/java/org/apache/lucene/codecs/KnnVectorsWriter.java:111]: I pushed a commit with what I had in mind. Essentially `cost()` and `size()` are the same thing on vectors except that the latter is expected to be accurate. Maybe we should rethink this, e.g. could `cost()` be required to be accurate on `VectorValues` instances, or could the base class make `cost()` final and delegate to `size()`?

Comment (rmuir) [reply lucene/core/src/java/org/apache/lucene/codecs/KnnVectorsWriter.java]: i'm happy either way, i'm not familiar enough with the specifics of the code, and I lean conservative when trying to fix issues before a release. we don't even have to touch it here now if there's no real risk of overflow (e.g. its just count of subs).

**Review by jpountz — APPROVED** [review]

**Comment by rmuir** [comment]
Thanks @jpountz for going thru the file with me!
