### PR TITLE
PrimaryNode: add configurable timeout to waitForAllRemotesToClose

### LINKED ISSUE #11674: PrimaryNode close waits for replicas to close, but there is no guarantee they ever will [LUCENE-10638]
We run Lucene Replicator to replicate a single primary to many replicas. In production, we have experienced downtime due to PrimaryNode.close never finishing.

 

For some unknown reason - incorrect exception handling? Replica hung forever? Reference counting bug? - the primary's CopyState ref count never reaches 0, and so close hangs forever. While obviously we should fix the underlying bug that prevents CopyState from being released correctly, in the meantime it is quite harmful to have PrimaryNode hang for a condition that may never happen. There are also operational possibilities that could cause this even without bugs, for example a replica that hangs forever.

 

PrimaryNode.close should have the option to avoid this situation. One possibility is to add a timeout - give replicas a configurable timeout to close cleanly, otherwise go forward with closing anyway.

 

In our case, all replicas must already handle errors on the primary (e.g. crash) so in fact closing immediately is not more harmful than any of these other situations we must handle anyway. One could argue that generally replicas must expect a primary could disappear at any time for any reason, and in that case, maybe waiting for replicas to close is unnecessary in the first place.

 

If we can build consensus around the right approach for a fix here, and committers don't have time to do so themselves, I am happy to assemble a PR.

---
Migrated from [LUCENE-10638](https://issues.apache.org/jira/browse/LUCENE-10638) by Steven Schlansker

### PR DESCRIPTION
**Pull request by stevenschlansker**
Adds a configurable timeout for PrimaryNode waiting for remotes to close.
The default matches existing behavior. In the long run, maybe this wait loop goes away entirely, but I elected to make the most compatible change first.

Fixes #11674

### CODE REVIEW

File: lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java [hunk 1]
```diff
@@ -196,6 +197,21 @@ public synchronized long getLastCommitVersion() {
...
+   */
+  public int getRemoteCloseTimeout() {
+    return remoteCloseTimeout;
+  }
+
+  /**
+   * Set the number of milliseconds to wait during shutdown for remote replicas to close. {@code -1}
+   * (the default) means forever, and {@code 0} means don't wait at all.
+   */
+  public void setRemoteCloseTimeout(int remoteCloseTimeout) {
```
Comment (zhaih) [inline lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java:211]: Can we add some unit tests for at least `remoteCloseTimeout = 0` case? Like produce some error or just interrupt the replicaNode and then close the primaryNode?

File: lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java [hunk 2]
```diff
@@ -61,6 +61,7 @@ public abstract class PrimaryNode extends Node {
   private CopyState copyState;
 
   protected final long primaryGen;
+  private int remoteCloseTimeout = -1;
```
Comment (zhaih) [inline lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java:64]: It'd better to name it `remoteCloseTimeoutMs`? And also change the getter and setter correspondingly?

**Review by zhaih — COMMENTED** [review]
Thanks for making the change, overall LGTM, just have some small comments.

Also please don't forget to add an entry in CHANGES.txt

File: lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java [hunk 3]
```diff
@@ -196,6 +197,21 @@ public synchronized long getLastCommitVersion() {
...
+  public int getRemoteCloseTimeout() {
+    return remoteCloseTimeout;
+  }
+
+  /**
+   * Set the number of milliseconds to wait during shutdown for remote replicas to close. {@code -1}
+   * (the default) means forever, and {@code 0} means don't wait at all.
+   */
+  public void setRemoteCloseTimeout(int remoteCloseTimeout) {
+    this.remoteCloseTimeout = remoteCloseTimeout;
```
Comment (mikemccand) [inline lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java:212]: Could we throw `IllegalArgumentException` if this is < -1?

File: lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java (hunk 1 above)
Comment (mikemccand) [reply lucene/replicator/src/java/org/apache/lucene/replicator/nrt/PrimaryNode.java:211]: In addition to a specific test case, we could also randomize the timeout we pass in our randomized tests.  Randomly sometimes pass 0, other times a random range or so.

**Review by mikemccand — APPROVED** [review]
This makes total sense -- tying Primary to the behavior of Replicas is dangerous coupling.  It would be great to fix/improve the design so that Primary never has to wait for Replicas to do anything, but let's start with this great baby step.

**Comment by stevenschlansker** [comment]
I updated this PR to rename the field to include `Ms`.
I added a test case for both no timeout (0), and 1000ms. I verified the test fails (doesn't terminate) without the new configuration option sent.

I don't think this is a great candidate for a random test - randomization is wonderful for perturbing data and finding edge cases in algorithms. In this case, it is just an int we compare to a clock, so randomizing doesn't seem likely to uncover any helpful edge cases. Please let me know if this is still desired.

File: lucene/CHANGES.txt [hunk 4]
```diff
@@ -44,6 +44,8 @@ New Features
 * LUCENE-10626 Hunspell: add tools to aid dictionary editing:
   analysis introspection, stem expansion and stem/flag suggestion (Peter Gromov)
 
+* GITHUB#11822: Configure replicator PrimaryNode replia shutdown timeout. (Steven Schlansker)
```
Comment (zhaih) [inline lucene/CHANGES.txt:47]: We can put it under 9.5 so it can be release in next release and don't need to wait until 10?

**Review by zhaih — APPROVED** [review]
Thanks @stevenschlansker LGTM, I think this change contains no backward breaking API change so we should make it in 9.5?

File: lucene/CHANGES.txt (hunk 4 above)
Comment (stevenschlansker) [reply lucene/CHANGES.txt]: Sounds great to me! I moved the CHANGES entry.

**Comment by zhaih** [comment]
I merged it but seems there're test failure
```
org.apache.lucene.index.TestIndexFileDeleter > test suite's output saved to /home/runner/work/lucene/lucene/lucene/core/build/test-results/test/outputs/OUTPUT-org.apache.lucene.index.TestIndexFileDeleter.txt, copied below:
   >     org.apache.lucene.store.AlreadyClosedException: ReaderPool is already closed
   >         at __randomizedtesting.SeedInfo.seed([FF62209E9305A732:16FF57ACE5CC40CF]:0)
   >         at app//org.apache.lucene.index.ReaderPool.get(ReaderPool.java:400)
   >         at app//org.apache.lucene.index.IndexWriter.writeReaderPool(IndexWriter.java:3922)
   >         at app//org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:592)
   >         at app//org.apache.lucene.index.IndexWriter$4.getReader(IndexWriter.java:6479)
   >         at app//org.apache.lucene.tests.index.RandomIndexWriter.getReader(RandomIndexWriter.java:488)
   >         at app//org.apache.lucene.tests.index.RandomIndexWriter.getReader(RandomIndexWriter.java:420)
   >         at app//org.apache.lucene.index.TestIndexFileDeleter.testExcInDecRef(TestIndexFileDeleter.java:485)
   >         at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >         at java.base@17.0.4.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
   >         at java.base@17.0.4.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >         at java.base@17.0.4.1/java.lang.reflect.Method.invoke(Method.java:568)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
   >         at app//org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
   >         at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at app//org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
   >         at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
   >         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
   >         at app//com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
   >         at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at app//org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
   >         at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   >         at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
   >         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at app//org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
   >         at app//org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
   >         at app//org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
   >         at app//org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
   >         at app//org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
   >         at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
   >         at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
   >         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
   >         at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
   >         at java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)
  2> NOTE: reproduce with: gradlew test --tests TestIndexFileDeleter.testExcInDecRef -Dtests.seed=FF62209E9305A732 -Dtests.locale=is-IS -Dtests.timezone=Africa/Maseru -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

But seems not related to this PR, I'll create another issue if that failure is reproducible.
Thanks @stevenschlansker !

**Comment by stevenschlansker** [comment]
OK - I did run `./gradlew check` so I don't think I broke anything, but please let me know if it does end up being related!

**Comment by zhaih** [comment]
I tried to reproduce the issue but couldn't. So likely a transient or
extremely rare test failure, and should not be related to the PR
