### PR TITLE
Speed up slow tests (#15212)

### LINKED ISSUE #15212: Speed up slow tests
### Description

The goal should be tests that run in < 1 second.

We've got some that are consistently slow:

```
  166.32s TestRescoreTopNQuery.testLateInteractionQuery (:lucene:core)
  50.10s TestFullPrecisionFloatVectorSimilarityValuesSource.testFullPrecisionVectorSimilarityDVS (:lucene:core)
  39.02s TestPriorityQueue.testRemovalsAndInsertions (:lucene:core)
  23.61s TestIndexOrDocValuesQuery.testUseIndexForSelectiveMultiValueQueries (:lucene:core)
  16.98s TestIndexedDISI.testRandom (:lucene:core)
  12.86s TestLateInteractionRescorer.testMissingLateIValues (:lucene:core)
  10.10s TestBlockMaxConjunction.testRandom (:lucene:core)
   8.98s TestIndexWriterExceptions.testRandomExceptions (:lucene:core)
   7.91s TestTermInSetQuery.testDuel (:lucene:core)
   7.22s TestLateInteractionFloatValuesSource.testValues (:lucene:core)
```

 some (like `TestIndexedDISI.testRandom`) are just occasionally slow, but the others on this list seem to consistently show up as the worst offenders

### Gradle command to reproduce

_No response_

### PR DESCRIPTION
**Pull request by dweiss**

### CODE REVIEW

File: lucene/core/src/test/org/apache/lucene/util/TestPriorityQueue.java [hunk 1]
```diff
@@ -208,57 +209,48 @@ public void testAddAllDoesNotFitIntoQueue() {
...
+
+    var reference = new java.util.PriorityQueue<Integer>();
+    var pq = new IntegerQueue(size);
+
+    Random localRandom = new Xoroshiro128PlusRandom(random().nextLong());
+
+    // Lucene's PriorityQueue.remove uses reference equality, not .equals to determine which
+    // elements
+    // to remove (!).
+    HashMap<Integer, Integer> ints = new HashMap<>();
```
Comment (dweiss) [inline lucene/core/src/test/org/apache/lucene/util/TestPriorityQueue.java:225]: This test had a huge iteration count, was checking tons of stuff unnecessarily... I rewrote it to just compare against Java's PriorityQueue... but it turned out that lucene's PriorityQueue.remove(T) is implemented as a linear scan through all elements, with reference equality (which is surprising to say the least...). That's why this "cache" of ints needs to be here.

PQ.remove is only used from one place within Lucene... maybe we should drop this method entirely (or at least change == to .equals to be less surprising?).

**Comment by rmuir** [comment]
I'll help with merging this branch out of conflicts: I'm not actually "fixing" anything in `main`, just `@Nightly`'ing the long tail as a cortisone shot. I probably cause some conflicts which will be easy to resolve.

**Comment by dweiss** [comment]
No worries, I'll handle the merge and conflicts.

File: lucene/core/src/test/org/apache/lucene/util/TestPriorityQueue.java (hunk 1 above)
Comment (rmuir) [reply lucene/core/src/test/org/apache/lucene/util/TestPriorityQueue.java:225]: +1 to open a followup issue on this!

Comment (dweiss) [reply lucene/core/src/test/org/apache/lucene/util/TestPriorityQueue.java:225]: https://github.com/apache/lucene/issues/15309

**Comment by dweiss** [comment]
I'll merge this in. There's been work on speeding up tests on other branches and indeed - we can just tackle them individually, on need for this branch.
